[en]
name = "100% Orange Juice"
icon = "100orangejuicewiki.png"

[[en.origin]]
name = "100% Orange Juice Fandom Wiki"
url = "100orangejuice.fandom.com"
mainpage = "100%_Orange_Juice_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "100% Orange Juice Fandom Wiki (Archive)"
url = "onehundredpercentorangejuice-archive.fandom.com"
mainpage = "100%_Orange_Juice_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "100% Orange Juice Wiki"
url = "orangejuice.wiki"
platform = "mediawiki"
icon = "100orangejuicewiki.png"
mainpage = "100%_Orange_Juice_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
