[en]
name = "18TRIP"
icon = "18tripwiki.png"

[[en.origin]]
name = "18TRIP Fandom Wiki"
url = "18trip.fandom.com"
mainpage = "18_TRIP_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "18TRIP Wiki"
host = "Miraheze"
url = "wiki.18t.rip"
platform = "mediawiki"
icon = "18tripwiki.png"
mainpage = "18TRIP_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
