[en]
name = "2XKO"
icon = "2xkowiki.png"

[[en.origin]]
name = "2XKO Fandom Wiki"
url = "2xko.fandom.com"
mainpage = "2XKO_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "2XKO Wiki"
url = "wiki.play2xko.com"
platform = "mediawiki"
icon = "2xkowiki.png"
mainpage = "Main_Page"
search-path = "/en-us/"
content-path = "/en-us/"
tags = [
    "official",
]
