[en]
name = "7 Days to Die"
icon = "7daystodiewiki.png"

[[en.origin]]
name = "7 Days to Die Fandom Wiki"
url = "7daystodie.fandom.com"
mainpage = "7_Days_to_Die_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "7 Days to Die Wiki"
host = "wiki.gg"
url = "7daystodie.wiki.gg"
platform = "mediawiki"
icon = "7daystodiewiki.png"
mainpage = "7_Days_to_Die_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
