[en]
name = "Abiotic Factor"
icon = "abioticfactor.png"

[[en.origin]]
name = "Abiotic Factor Fandom Wiki"
url = "abiotic-factor.fandom.com"
mainpage = "Abiotic_Factor_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Abiotic Factor Wiki"
host = "wiki.gg"
url = "abioticfactor.wiki.gg"
platform = "mediawiki"
icon = "abioticfactor.png"
mainpage = "Abiotic_Factor_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
