[en]
name = "Advance Wars"
icon = "warswiki.png"

[[en.origin]]
name = "Advance Wars Fandom Wiki"
url = "advancewars.fandom.com"
mainpage = "Advance_Wars_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Advance Wars Neoseeker Wiki"
url = "advancewars.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Wars Wiki"
url = "warswiki.org"
platform = "mediawiki"
icon = "warswiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
