[en]
origins_label = "Advance Wars Fandom Wiki"
destination = "Wars Wiki"
destination_base_url = "warswiki.org"
destination_platform = "mediawiki"
destination_icon = "warswiki.png"
destination_main_page = "Main_Page"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"

[[en.origins]]
origin = "Advance Wars Fandom Wiki"
origin_base_url = "advancewars.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Advance_Wars_Wiki"

[[en.origins]]
origin = "Advance Wars Neoseeker Wiki"
origin_base_url = "advancewars.neoseeker.com"
origin_content_path = "/wiki/"
origin_main_page = "Main_Page"
