[en]
origins_label = "A Hat in Time Fandom Wiki"
destination = "A Hat in Time Wiki"
destination_base_url = "ahatintime.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "ahatintimewiki.png"
destination_main_page = "A_Hat_in_Time_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "A Hat in Time Fandom Wiki"
origin_base_url = "ahatintime.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "A_Hat_in_Time_Wiki"
