[en]
origins_label = "Akudama Drive Fandom Wiki"
destination = "Akudama Drive Wiki"
destination_base_url = "akudamadrive.miraheze.org"
destination_platform = "mediawiki"
destination_icon = "akudamadrivewiki.png"
destination_main_page = "Akudama_Drive_Wiki"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"
destination_host = "Miraheze"

[[en.origins]]
origin = "Akudama Drive Fandom Wiki"
origin_base_url = "akudamadrive.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Akudama_Drive_Wiki"
