[en]
name = "Aloft"
icon = "aloft.png"

[[en.origin]]
name = "Aloft Fandom Wiki"
url = "aloft.fandom.com"
mainpage = "Aloft_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Aloft Wiki"
host = "wiki.gg"
url = "aloft.wiki.gg"
platform = "mediawiki"
icon = "aloft.png"
mainpage = ""
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
