[en]
name = "AlphaVer"
icon = "alphaverwiki.png"

[[en.origin]]
name = "AlphaVer Fandom Wiki"
url = "alphaver.fandom.com"
mainpage = "AlphaVer_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "AlphaVer Wiki"
host = "Miraheze"
url = "alphaver.miraheze.org"
platform = "mediawiki"
icon = "alphaverwiki.png"
mainpage = "AlphaVer_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
