[en]
origins_label = "Plants vs. Zombies 2: Alternate UniverZ Fandom Wiki"
destination = "Plants vs. Zombies 2: Alternate UniverZ Wiki"
destination_base_url = "altverz.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "altverzwiki.png"
destination_main_page = "Plants_vs._Zombies_2:_Alternate_UniverZ_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Plants vs. Zombies 2: Alternate UniverZ Fandom Wiki"
origin_base_url = "altverz.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Plants_vs._Zombies_2:_Alternate_UniverZ_Wiki"
