[es]
name = "amiibopedia"
icon = "amiibopedia.png"

[[es.origin]]
name = "amiibopedia Fandom Wiki"
url = "amiibo.fandom.com/es"
mainpage = "Amiibopedia"
content-path = "/wiki/"

[[es.destination]]
name = "amiibopedia"
url = "es.amiibopedia.com"
platform = "mediawiki"
icon = "amiibopedia.png"
mainpage = "Amiibopedia"
search-path = "/index.php"
content-path = "/wiki/"
