[en]
name = "Android"
icon = "androidwiki.png"

[[en.origin]]
name = "Android Fandom Wiki"
url = "android.fandom.com"
mainpage = "Android_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Android Wiki"
host = "Miraheze"
url = "androidwiki.info"
platform = "mediawiki"
icon = "androidwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
