[en]
origins_label = "Animal Crossing: Pocket Camp Fandom Wiki"
destination = "Animal Crossing: Pocket Camp Wiki"
destination_base_url = "animalcrossingpocketcamp.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "animalcrossingpocketcampwiki.png"
destination_main_page = "Animal_Crossing:_Pocket_Camp_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Animal Crossing: Pocket Camp Fandom Wiki"
origin_base_url = "animalcrossingpocketcamp.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Animal_Crossing:_Pocket_Camp_Wiki"
