[en]
name = "Super Animal Royale"
icon = "animalroyalewiki.png"

[[en.origin]]
name = "Super Animal Royale Fandom Wiki"
url = "animalroyale.fandom.com"
mainpage = "Super_Animal_Royale_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Super Animal Royale Wiki"
host = "Miraheze"
url = "wiki.animalroyale.com"
platform = "mediawiki"
icon = "animalroyalewiki.png"
mainpage = "Super_Animal_Royale_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
