[en]
name = "Another Eden"
icon = "anothereden.png"

[[en.origin]]
name = "Another Eden Fandom Wiki"
url = "anothereden.fandom.com"
mainpage = "Another_Eden_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Another Eden Wiki"
url = "anothereden.wiki"
platform = "mediawiki"
icon = "anothereden.png"
mainpage = "Another_Eden_Wiki"
search-path = "/index.php"
content-path = "/w/"
tags = [
    "recommended",
]
