[en]
name = "AntonBlast"
icon = "summitpedia.png"

[[en.origin]]
name = "AntonBlast Fandom Wiki"
url = "antonblastpedia.fandom.com"
mainpage = "AntonBlast_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Antonball Fandom Wiki"
url = "antonball.fandom.com"
mainpage = "Antonball_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Summitpedia"
host = "Miraheze"
url = "summitpedia.miraheze.org"
platform = "mediawiki"
icon = "summitpedia.png"
mainpage = "Summitpedia:Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
