[en]
name = "Apex Legends"
icon = "apexlegendswiki.png"

[[en.origin]]
name = "Apex Legends Fandom Wiki"
url = "apexlegends.fandom.com"
mainpage = "Apex_Legends_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Apex Legends Fandom Wiki (Archive)"
url = "apex--legends-archive.fandom.com"
mainpage = "Apexlegends_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Apex Legends Wiki"
host = "wiki.gg"
url = "apexlegends.wiki.gg"
platform = "mediawiki"
icon = "apexlegendswiki.png"
mainpage = "Apex_Legends_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
