[fr]
name = "Arcane"
icon = "wikiarcane.png"

[[fr.origin]]
name = "Arcane Fandom Wiki"
url = "wiki-arcane.fandom.com/fr"
mainpage = "Wiki_Wiki_Arcane"
content-path = "/wiki/"

[[fr.destination]]
name = "Arcane Wiki"
host = "Miraheze"
url = "arcanefr.miraheze.org"
platform = "mediawiki"
icon = "wikiarcane.png"
mainpage = "Accueil"
search-path = "/w/index.php"
content-path = "/wiki/"
