[de]
origins_label = "ARK Fandom Wiki"
destination = "ARK Wiki"
destination_base_url = "ark.wiki.gg/de"
destination_platform = "mediawiki"
destination_icon = "arkwiki.png"
destination_main_page = "ARK_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[de.origins]]
origin = "ARK Fandom Wiki"
origin_base_url = "ark.fandom.com/de"
origin_content_path = "/wiki/"
origin_main_page = "ARK_Survival_Evolved_Wiki"

[ru]
origins_label = "ARK Fandom Wiki"
destination = "ARK Wiki"
destination_base_url = "ark.wiki.gg/ru"
destination_platform = "mediawiki"
destination_icon = "arkwiki.png"
destination_main_page = "ARK_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[ru.origins]]
origin = "ARK Fandom Wiki"
origin_base_url = "ark.fandom.com/ru"
origin_content_path = "/wiki/"
origin_main_page = "ARK_Survival_Evolved_Wiki"

[th]
origins_label = "ARK Survival Evolved Fandom Wiki"
destination = "ARK Wiki"
destination_base_url = "ark.wiki.gg/th"
destination_platform = "mediawiki"
destination_icon = "arkwiki.png"
destination_main_page = "ARK_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[th.origins]]
origin = "ARK Survival Evolved Fandom Wiki"
origin_base_url = "ark.fandom.com/th"
origin_content_path = "/wiki/"
origin_main_page = "ARK_Survival_Evolved_Wiki"

[es]
origins_label = "ARK Fandom Wiki"
destination = "ARK Wiki"
destination_base_url = "ark.wiki.gg/es"
destination_platform = "mediawiki"
destination_icon = "arkwiki.png"
destination_main_page = "ARK_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[es.origins]]
origin = "ARK Fandom Wiki"
origin_base_url = "ark.fandom.com/es"
origin_content_path = "/wiki/"
origin_main_page = "ARK_Survival_Evolved_Wiki"

[en]
origins_label = "ARK Fandom Wikis"
destination = "ARK Wiki"
destination_base_url = "ark.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "arkwiki.png"
destination_main_page = "ARK_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[en.origins]]
origin = "ARK Fandom Wiki"
origin_base_url = "ark.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "ARK_Survival_Evolved_Wiki"

[[en.origins]]
origin = "ARK Fandom Wiki"
origin_base_url = "ark-survival-evolved-archive.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "ARK_Survival_Evolved_Wiki"

[pt]
origins_label = "ARK Fandom Wiki"
destination = "ARK Wiki"
destination_base_url = "ark.wiki.gg/pt-br"
destination_platform = "mediawiki"
destination_icon = "arkwiki.png"
destination_main_page = "ARK_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[pt.origins]]
origin = "ARK Fandom Wiki"
origin_base_url = "ark.fandom.com/pt-br"
origin_content_path = "/wiki/"
origin_main_page = "ARK_Survival_Evolved_Wiki"

[ja]
origins_label = "ARK Fandom Wiki"
destination = "ARK Wiki"
destination_base_url = "ark.wiki.gg/ja"
destination_platform = "mediawiki"
destination_icon = "arkwiki.png"
destination_main_page = "ARK_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[ja.origins]]
origin = "ARK Fandom Wiki"
origin_base_url = "ark.fandom.com/ja"
origin_content_path = "/wiki/"
origin_main_page = "ARK_Survival_Evolved_Wiki"

[it]
origins_label = "ARK Fandom Wiki"
destination = "ARK Wiki"
destination_base_url = "ark.wiki.gg/it"
destination_platform = "mediawiki"
destination_icon = "arkwiki.png"
destination_main_page = "ARK_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[it.origins]]
origin = "ARK Fandom Wiki"
origin_base_url = "ark.fandom.com/it"
origin_content_path = "/wiki/"
origin_main_page = "ARK_Survival_Evolved_Wiki"

[pl]
origins_label = "ARK Fandom Wiki"
destination = "ARK Wiki"
destination_base_url = "ark.wiki.gg/pl"
destination_platform = "mediawiki"
destination_icon = "arkwiki.png"
destination_main_page = "ARK_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[pl.origins]]
origin = "ARK Fandom Wiki"
origin_base_url = "ark.fandom.com/pl"
origin_content_path = "/wiki/"
origin_main_page = "ARK_Survival_Evolved_Wiki"

[fr]
origins_label = "ARK Fandom Wiki"
destination = "ARK Wiki"
destination_base_url = "ark.wiki.gg/fr"
destination_platform = "mediawiki"
destination_icon = "arkwiki.png"
destination_main_page = "ARK_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[fr.origins]]
origin = "ARK Fandom Wiki"
origin_base_url = "ark.fandom.com/fr"
origin_content_path = "/wiki/"
origin_main_page = "ARK_Survival_Evolved_Wiki"
