[de]
name = "ARK"
icon = "arkwiki.png"

[[de.origin]]
name = "ARK Fandom Wiki"
url = "ark.fandom.com/de"
mainpage = "ARK_Survival_Evolved_Wiki"
content-path = "/wiki/"

[[de.destination]]
name = "ARK Wiki"
host = "wiki.gg"
url = "ark.wiki.gg/de"
platform = "mediawiki"
icon = "arkwiki.png"
mainpage = "ARK_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[ru]
name = "ARK"
icon = "arkwiki.png"

[[ru.origin]]
name = "ARK Fandom Wiki"
url = "ark.fandom.com/ru"
mainpage = "ARK_Survival_Evolved_Wiki"
content-path = "/wiki/"

[[ru.destination]]
name = "ARK Wiki"
host = "wiki.gg"
url = "ark.wiki.gg/ru"
platform = "mediawiki"
icon = "arkwiki.png"
mainpage = "ARK_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[th]
name = "ARK Survival Evolved"
icon = "arkwiki.png"

[[th.origin]]
name = "ARK Survival Evolved Fandom Wiki"
url = "ark.fandom.com/th"
mainpage = "ARK_Survival_Evolved_Wiki"
content-path = "/wiki/"

[[th.destination]]
name = "ARK Wiki"
host = "wiki.gg"
url = "ark.wiki.gg/th"
platform = "mediawiki"
icon = "arkwiki.png"
mainpage = "ARK_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[es]
name = "ARK"
icon = "arkwiki.png"

[[es.origin]]
name = "ARK Fandom Wiki"
url = "ark.fandom.com/es"
mainpage = "ARK_Survival_Evolved_Wiki"
content-path = "/wiki/"

[[es.destination]]
name = "ARK Wiki"
host = "wiki.gg"
url = "ark.wiki.gg/es"
platform = "mediawiki"
icon = "arkwiki.png"
mainpage = "ARK_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[en]
name = "ARK"
icon = "arkwiki.png"

[[en.origin]]
name = "ARK Fandom Wiki"
url = "ark.fandom.com"
mainpage = "ARK_Survival_Evolved_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "ARK Fandom Wiki"
url = "ark-survival-evolved-archive.fandom.com"
mainpage = "ARK_Survival_Evolved_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "ARK Wiki"
host = "wiki.gg"
url = "ark.wiki.gg"
platform = "mediawiki"
icon = "arkwiki.png"
mainpage = "ARK_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[pt]
name = "ARK"
icon = "arkwiki.png"

[[pt.origin]]
name = "ARK Fandom Wiki"
url = "ark.fandom.com/pt-br"
mainpage = "ARK_Survival_Evolved_Wiki"
content-path = "/wiki/"

[[pt.destination]]
name = "ARK Wiki"
host = "wiki.gg"
url = "ark.wiki.gg/pt-br"
platform = "mediawiki"
icon = "arkwiki.png"
mainpage = "ARK_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[ja]
name = "ARK"
icon = "arkwiki.png"

[[ja.origin]]
name = "ARK Fandom Wiki"
url = "ark.fandom.com/ja"
mainpage = "ARK_Survival_Evolved_Wiki"
content-path = "/wiki/"

[[ja.destination]]
name = "ARK Wiki"
host = "wiki.gg"
url = "ark.wiki.gg/ja"
platform = "mediawiki"
icon = "arkwiki.png"
mainpage = "ARK_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[it]
name = "ARK"
icon = "arkwiki.png"

[[it.origin]]
name = "ARK Fandom Wiki"
url = "ark.fandom.com/it"
mainpage = "ARK_Survival_Evolved_Wiki"
content-path = "/wiki/"

[[it.destination]]
name = "ARK Wiki"
host = "wiki.gg"
url = "ark.wiki.gg/it"
platform = "mediawiki"
icon = "arkwiki.png"
mainpage = "ARK_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[pl]
name = "ARK"
icon = "arkwiki.png"

[[pl.origin]]
name = "ARK Fandom Wiki"
url = "ark.fandom.com/pl"
mainpage = "ARK_Survival_Evolved_Wiki"
content-path = "/wiki/"

[[pl.destination]]
name = "ARK Wiki"
host = "wiki.gg"
url = "ark.wiki.gg/pl"
platform = "mediawiki"
icon = "arkwiki.png"
mainpage = "ARK_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[fr]
name = "ARK"
icon = "arkwiki.png"

[[fr.origin]]
name = "ARK Fandom Wiki"
url = "ark.fandom.com/fr"
mainpage = "ARK_Survival_Evolved_Wiki"
content-path = "/wiki/"

[[fr.destination]]
name = "ARK Wiki"
host = "wiki.gg"
url = "ark.wiki.gg/fr"
platform = "mediawiki"
icon = "arkwiki.png"
mainpage = "ARK_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
