[en]
name = "EXA_PICO Universe"
icon = "exapicowiki.png"

[[en.origin]]
name = "EXA_PICO Universe Fandom Wiki"
url = "artonelico.fandom.com"
mainpage = "The_EXA_PICO_Universe_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "EXA_PICO Wiki"
host = "wiki.gg"
url = "exapico.wiki.gg"
platform = "mediawiki"
icon = "exapicowiki.png"
mainpage = "The_EXA_PICO_Universe_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
