[en]
name = "Ashes of Creation"
icon = "ashesofcreationwiki.png"

[[en.origin]]
name = "Ashes of Creation Fandom Wiki"
url = "ashesofcreation.fandom.com"
mainpage = "Ashes_of_Creation_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Ashes of Creation Fandom Wiki (Archived)"
url = "ashesofcreation-archive.fandom.com"
mainpage = "Ashes_of_Creation_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Ashes of Creation Wiki"
url = "ashesofcreation.wiki"
platform = "mediawiki"
icon = "ashesofcreationwiki.png"
mainpage = "Ashes_of_Creation_Wiki"
search-path = "/index.php"
content-path = "/"
