[en]
name = "Assault Android Cactus"
icon = "assaultandroidcactuswiki.png"

[[en.origin]]
name = "Assault Android Cactus Fandom Wiki"
url = "assault-android-cactus.fandom.com"
mainpage = "Assault_Android_Cactus_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Assault Android Cactus Wiki"
host = "Miraheze"
url = "assaultandroidcactus.miraheze.org"
platform = "mediawiki"
icon = "assaultandroidcactuswiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
