[en]
origins_label = "Atlyss Fandom Wiki"
destination = "ATLYSS Wiki"
destination_base_url = "atlyss.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "atlysswiki.png"
destination_main_page = "ATLYSS_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[en.origins]]
origin = "Atlyss Fandom Wiki"
origin_base_url = "atlyss.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Atlyss_Wiki"
