[en]
name = "Atlyss"
icon = "atlysswiki.png"

[[en.origin]]
name = "Atlyss Fandom Wiki"
url = "atlyss.fandom.com"
mainpage = "Atlyss_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "ATLYSS Wiki"
host = "wiki.gg"
url = "atlyss.wiki.gg"
platform = "mediawiki"
icon = "atlysswiki.png"
mainpage = "ATLYSS_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
