[en]
name = "Backpack Hero"
icon = "backpackherowiki.png"

[[en.origin]]
name = "Backpack Hero Fandom Wiki"
url = "backpack-hero.fandom.com"
mainpage = "Backpack_Hero_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Backpack Hero Wiki"
host = "wiki.gg"
url = "backpackhero.wiki.gg"
platform = "mediawiki"
icon = "backpackherowiki.png"
mainpage = "Backpack_Hero_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
