[en]
name = "Bakugan"
icon = "bakugan.png"

[[en.origin]]
name = "Bakugan Fandom Wiki"
url = "bakugan.fandom.com"
mainpage = "Bakugan_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Bakugan Wiki"
url = "bakugan.wiki"
platform = "mediawiki"
icon = "bakugan.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
