[en]
origins_label = "Bakugan Fandom Wiki"
destination = "Bakugan Wiki"
destination_base_url = "bakugan.wiki"
destination_platform = "mediawiki"
destination_icon = "bakugan.png"
destination_main_page = "Main_Page"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"

[[en.origins]]
origin = "Bakugan Fandom Wiki"
origin_base_url = "bakugan.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Bakugan_Wiki"
