[en]
name = "Balatro"
icon = "balatro.png"

[[en.origin]]
name = "Balatro Fandom Wiki"
url = "balatrogame.fandom.com"
mainpage = "Balatro_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Balatro Wiki"
url = "balatrowiki.org"
platform = "mediawiki"
icon = "balatro.png"
mainpage = ""
search-path = "/"
content-path = "/w/"
tags = [
    "recommended",
]
