[en]
name = "BallisticNG"
icon = "ballisticngwiki.png"

[[en.origin]]
name = "BallisticNG Fandom Wiki"
url = "ballisticng.fandom.com"
mainpage = "BallisticNG_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "BallisticNG Wiki"
host = "Miraheze"
url = "ballisticng.miraheze.org"
platform = "mediawiki"
icon = "ballisticngwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
