[en]
name = "Banjo-Kazooie"
icon = "jiggywikki.png"

[[en.origin]]
name = "Banjo-Kazooie Fandom Wiki"
url = "banjokazooie.fandom.com"
mainpage = "Banjo-Kazooie_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Banjo-Kazooie Wiki - Neoseeker"
url = "banjokazooie.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Jiggywikki"
url = "banjokazooiewiki.com"
platform = "mediawiki"
icon = "jiggywikki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
