[en]
name = "Battle Cats"
icon = "battlecats.png"

[[en.origin]]
name = "Battle Cats Fandom Wiki"
url = "battle-cats.fandom.com"
mainpage = "Battle_Cats_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Battle Cats Wiki"
host = "Miraheze"
url = "battlecats.miraheze.org"
platform = "mediawiki"
icon = "battlecats.png"
mainpage = "Battle_Cats_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
