[fr]
name = "Battlestar"
icon = "battlestarwiki.png"

[[fr.origin]]
name = "Battlestar Fandom Wiki"
url = "galactica.fandom.com/fr"
mainpage = "Accueil"
content-path = "/wiki/"

[[fr.destination]]
name = "Battlestar Wiki"
url = "fr.battlestarwiki.ddns.net"
platform = "mediawiki"
icon = "battlestarwiki.png"
mainpage = "Accueil"
search-path = "/index.php"
content-path = "/wiki/"
