[en]
name = "Konami Music"
icon = "remywiki.png"

[[en.origin]]
name = "Beatmania Fandom Wiki"
url = "beatmania.fandom.com"
mainpage = "Beatmania_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Dance Dance Revolution Fandom Wiki"
url = "dancedancerevolution.fandom.com"
mainpage = "Dance_Dance_Revolution_(DDR)_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "jubeat Fandom Wiki"
url = "jubeat.fandom.com"
mainpage = "Jubeat_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Konami Music Video Game Fandom Wiki"
url = "bemani.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "RemyWiki"
url = "remywiki.com"
platform = "mediawiki"
icon = "remywiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/"
tags = [
    "recommended",
]
