[en]
name = "Binding of Isaac: Revelations"
icon = "bindingofisaacrevelationswiki.png"

[[en.origin]]
name = "Binding of Isaac: Revelations Fandom Wiki"
url = "tboirevelations.fandom.com"
mainpage = "The_Binding_of_Isaac:_Revelations_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Binding of Isaac Revelations Wiki"
host = "wiki.gg"
url = "tboirevelations.wiki.gg"
platform = "mediawiki"
icon = "bindingofisaacrevelationswiki.png"
mainpage = "The_Binding_of_Isaac:_Revelations_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
