[en]
name = "Bionicle"
icon = "biosector01.png"

[[en.origin]]
name = "Bionicle Fandom Wiki"
url = "bionicle.fandom.com"
mainpage = "The_Bionicle_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "BIONICLEsector01"
url = "biosector01.com"
platform = "mediawiki"
icon = "biosector01.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
