[en]
name = "BitCraft"
icon = "bitcraftwiki.png"

[[en.origin]]
name = "BitCraft Fandom Wiki"
url = "bitcraft.fandom.com"
mainpage = "BitCraft_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "BitCraft Wiki"
host = "wiki.gg"
url = "bitcraft.wiki.gg"
platform = "mediawiki"
icon = "bitcraftwiki.png"
mainpage = "BitCraft_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
