[en]
name = "Blade & Sorcery"
icon = "bladeandsorcery.png"

[[en.origin]]
name = "Blade & Sorcery Fandom Wiki"
url = "blade-and-sorcery.fandom.com"
mainpage = "Blade_and_Sorcery_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Blade & Sorcery Wiki"
host = "wiki.gg"
url = "bladeandsorcery.wiki.gg"
platform = "mediawiki"
icon = "bladeandsorcery.png"
mainpage = "Blade_%26_Sorcery_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
