[en]
name = "BlazBlue"
icon = "blazblue.png"

[[en.origin]]
name = "BlazBlue Fandom Wiki"
url = "blazblue.fandom.com"
mainpage = "BlazBlue_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "BlazBlue Wiki"
url = "blazblue.wiki"
platform = "mediawiki"
icon = "blazblue.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
