[en]
name = "BlockFrontMC"
icon = "blockfrontwiki.png"

[[en.origin]]
name = "BlockFrontMC Fandom Wiki"
url = "blockfrontmc.fandom.com"
mainpage = "BlockFrontMC_Wikia"
content-path = "/wiki/"

[[en.destination]]
name = "BlockFrontMC Wiki"
host = "wiki.gg"
url = "blockfront.wiki.gg"
platform = "mediawiki"
icon = "blockfrontwiki.png"
mainpage = "BlockFront_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
