[en]
name = "Book of Travels"
icon = "bookoftravelswiki.png"

[[en.origin]]
name = "Book of Travels Fandom Wiki"
url = "bookoftravels.fandom.com"
mainpage = "Book_of_Travels_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Book of Travels Wiki"
host = "wiki.gg"
url = "bookoftravels.wiki.gg"
platform = "mediawiki"
icon = "bookoftravelswiki.png"
mainpage = "Book_of_Travels_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
