[en]
name = "Brawlhalla"
icon = "brawlhallawiki.png"

[[en.origin]]
name = "Brawlhalla Fandom Wiki"
url = "brawlhalla.fandom.com"
mainpage = "Brawlhalla_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Brawlhalla Wiki"
host = "wiki.gg"
url = "brawlhalla.wiki.gg"
platform = "mediawiki"
icon = "brawlhallawiki.png"
mainpage = "Brawlhalla_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
