[en]
origins_label = "Brighter Shores Fandom Wikis"
destination = "Brighter Shores Wiki"
destination_base_url = "brightershoreswiki.org"
destination_platform = "mediawiki"
destination_icon = "brightershoreswiki.png"
destination_main_page = "Main_Page"
destination_search_path = "/"
destination_content_path = "/w/"

[[en.origins]]
origin = "Brighter-Shores Fandom Wiki"
origin_base_url = "brighter-shores.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Brighter_Shores_Wiki"

[[en.origins]]
origin = "Brighter Shores Fandom Wiki"
origin_base_url = "brightershores.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Brighter_Shores_Wiki"
