[en]
name = "Brutal Orchestra"
icon = "brutalorchestrawiki.png"

[[en.origin]]
name = "Brutal Orchestra Fandom Wiki"
url = "hbbrutalorchestra.fandom.com"
mainpage = "Brutal_Orchestra_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Brutal Orchestra Wiki"
host = "wiki.gg"
url = "brutalorchestra.wiki.gg"
platform = "mediawiki"
icon = "brutalorchestrawiki.png"
mainpage = "Brutal_Orchestra_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
