[en]
name = "Bubsy Bobcat"
icon = "bubsypedia.png"

[[en.origin]]
name = "Bubsy Bobcat Fandom Wiki"
url = "bubsy.fandom.com"
mainpage = "Bubsy_Bobcat_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Bubsypedia"
host = "Miraheze"
url = "bubsypedia.miraheze.org"
platform = "mediawiki"
icon = "bubsypedia.png"
mainpage = "Bubsypedia"
search-path = "/w/index.php"
content-path = "/wiki/"
