[en]
name = "Camerapedia"
icon = "camerawiki.png"

[[en.origin]]
name = "Camerapedia Fandom Wiki"
url = "camerapedia.fandom.com"
mainpage = "Camerapedia"
content-path = "/wiki/"

[[en.destination]]
name = "Camera-wiki.org"
url = "camera-wiki.org"
platform = "mediawiki"
icon = "camerawiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
