[en]
name = "Catacomb"
icon = "catacombwiki.png"

[[en.origin]]
name = "Catacomb Fandom Wiki"
url = "catacomb.fandom.com"
mainpage = "Catacomb_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Catacomb Wiki"
host = "Miraheze"
url = "catacomb.miraheze.org"
platform = "mediawiki"
icon = "catacombwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
