[en]
name = "Celeste"
icon = "celeste.png"

[[en.origin]]
name = "Celeste Fandom Wiki"
url = "celestegame.fandom.com"
mainpage = "Celeste_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Celeste Wiki"
host = "Miraheze"
url = "celeste.ink"
platform = "mediawiki"
icon = "celeste.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
