[en]
name = "Cerasus"
icon = "cerasuswiki.png"

[[en.origin]]
name = "Cerasus Fandom Wiki"
url = "cerasus.fandom.com"
mainpage = "Cerasus_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Cerasus Wiki"
url = "yume.wiki"
platform = "mediawiki"
icon = "cerasuswiki.png"
mainpage = "Cerasus_Wiki"
search-path = "/index.php"
content-path = "/"
