[en]
name = "Chef RPG"
icon = "chefrpgwiki.png"

[[en.origin]]
name = "Chef RPG Fandom Wiki"
url = "chef-rpg.fandom.com"
mainpage = "Chef_RPG_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Chef RPG Wiki"
host = "wiki.gg"
url = "chefrpg.wiki.gg"
platform = "mediawiki"
icon = "chefrpgwiki.png"
mainpage = "Chef_RPG_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
