[en]
name = "Chrono"
icon = "chrono.png"

[[en.origin]]
name = "Chrono Fandom Wiki"
url = "chrono.fandom.com"
mainpage = "Chronopedia"
content-path = "/wiki/"

[[en.origin]]
name = "Chrono Wiki - Neoseeker"
url = "chrono.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Chrono Wiki"
url = "www.chronowiki.org"
platform = "mediawiki"
icon = "chrono.png"
mainpage = "Chrono_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
