[en]
name = "CITY"
icon = "city.png"

[[en.origin]]
name = "CITY Fandom Wiki"
url = "citymanga.fandom.com"
mainpage = "CITY_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "CITY Wiki"
host = "wiki.gg"
url = "city.wiki.gg"
platform = "mediawiki"
icon = "city.png"
mainpage = "CITY_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
