[es]
name = "Clash of Clans"
icon = "clashofclans.png"

[[es.origin]]
name = "Clash of Clans Fandom Wiki"
url = "clashofclans.fandom.com/es"
mainpage = "Wiki_Clash_of_Clans_en_Español"
content-path = "/wiki/"

[[es.destination]]
name = "Wiki Clash of Clans"
host = "wiki.gg"
url = "clashofclans.wiki.gg/es"
platform = "mediawiki"
icon = "clashofclans.png"
mainpage = "Wiki_Clash_of_Clans_en_Español"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]

[fr]
name = "Clash of Clans"
icon = "clashofclans.png"

[[fr.origin]]
name = "Clash of Clans Fandom Wiki"
url = "clashofclans.fandom.com/fr"
mainpage = "Wiki_Clash_of_Clans"
content-path = "/wiki/"

[[fr.destination]]
name = "Clash of Clans Wiki"
url = "wiki.clashofclans.fr"
platform = "mediawiki"
icon = "clashofclans.png"
mainpage = "Accueil"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
