[es]
origins_label = "Clash of Clans Fandom Wiki"
destination = "Wiki Clash of Clans"
destination_base_url = "clashofclans.wiki.gg/es"
destination_platform = "mediawiki"
destination_icon = "clashofclans.png"
destination_main_page = "Wiki_Clash_of_Clans_en_Español"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[es.origins]]
origin = "Clash of Clans Fandom Wiki"
origin_base_url = "clashofclans.fandom.com/es"
origin_content_path = "/wiki/"
origin_main_page = "Wiki_Clash_of_Clans_en_Español"

[fr]
origins_label = "Clash of Clans Fandom Wiki"
destination = "Clash of Clans Wiki"
destination_base_url = "wiki.clashofclans.fr"
destination_platform = "mediawiki"
destination_icon = "clashofclans.png"
destination_main_page = "Accueil"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"

[[fr.origins]]
origin = "Clash of Clans Fandom Wiki"
origin_base_url = "clashofclans.fandom.com/fr"
origin_content_path = "/wiki/"
origin_main_page = "Wiki_Clash_of_Clans"
