[en]
name = "CloverPit"
icon = "cloverpit.png"

[[en.origin]]
name = "CloverPit Fandom Wiki"
url = "cloverpit.fandom.com"
mainpage = "CloverPit_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "CloverPit Fandom Wiki"
url = "cloverpit-panik.fandom.com"
mainpage = "Clover_Pit_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "CloverPit Wiki"
host = "wiki.gg"
url = "cloverpit.wiki.gg"
platform = "mediawiki"
icon = "cloverpit.png"
mainpage = "CloverPit_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
