[en]
name = "Conway's Game of Life"
icon = "lifewiki.png"

[[en.origin]]
name = "Conway's Game of Life Fandom Wiki"
url = "conways-game-of-life.fandom.com"
mainpage = "Conway's_Game_of_Life_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "LifeWiki"
url = "conwaylife.com"
platform = "mediawiki"
icon = "lifewiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
