[en]
origins_label = "Conway's Game of Life Fandom Wiki"
destination = "LifeWiki"
destination_base_url = "conwaylife.com"
destination_platform = "mediawiki"
destination_icon = "lifewiki.png"
destination_main_page = "Main_Page"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"

[[en.origins]]
origin = "Conway's Game of Life Fandom Wiki"
origin_base_url = "conways-game-of-life.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Conway's_Game_of_Life_Wiki"
