[en]
name = "Cookie Run"
icon = "cookierunwiki.png"

[[en.origin]]
name = "Cookie Run Fandom Wiki"
url = "cookierun.fandom.com"
mainpage = "Cookie_Run_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Cookie Run: Kingdom Fandom Wiki"
url = "cookierunkingdom.fandom.com"
mainpage = "Cookie_Run:_Kingdom_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Cookie Run: Tower of Adventures Fandom Wiki"
url = "cookieruntoa.fandom.com"
mainpage = "Cookie_Run:_Tower_of_Adventures_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Cookie Run: Witch's Castle Fandom Wiki"
url = "cookierun-witchs-castle.fandom.com"
mainpage = "CookieRun:_Witch's_Castle_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Cookie Run Wiki"
url = "cookierun.wiki"
platform = "mediawiki"
icon = "cookierunwiki.png"
mainpage = "Cookie_Run_Wiki"
search-path = "/mw/index.php"
content-path = "/w/"
