[zh]
name = "Cookie"
icon = "cookiewiki.png"

[[zh.origin]]
name = "Cookie Fandom Wiki"
url = "cookie.fandom.com/zh"
mainpage = "首页"
content-path = "/wiki/"

[[zh.destination]]
name = "Cookie☆Wiki"
url = "cookie.wiki"
platform = "mediawiki"
icon = "cookiewiki.png"
mainpage = "首页"
search-path = "/index.php"
content-path = "/"
