[es]
origins_label = "Coromon Fandom Wiki"
destination = "Coromon Wiki"
destination_base_url = "coromon.wiki.gg/es"
destination_platform = "mediawiki"
destination_icon = "coromonwiki.png"
destination_main_page = "Coromon_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[es.origins]]
origin = "Coromon Fandom Wiki"
origin_base_url = "coromon.fandom.com/es"
origin_content_path = "/wiki/"
origin_main_page = "Coromon_Wiki"

[en]
origins_label = "Coromon Fandom Wiki"
destination = "Coromon Wiki"
destination_base_url = "coromon.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "coromonwiki.png"
destination_main_page = "Coromon_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[en.origins]]
origin = "Coromon Fandom Wiki"
origin_base_url = "coromon.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Coromon_Wiki"
