[es]
name = "Coromon"
icon = "coromonwiki.png"

[[es.origin]]
name = "Coromon Fandom Wiki"
url = "coromon.fandom.com/es"
mainpage = "Coromon_Wiki"
content-path = "/wiki/"

[[es.destination]]
name = "Coromon Wiki"
host = "wiki.gg"
url = "coromon.wiki.gg/es"
platform = "mediawiki"
icon = "coromonwiki.png"
mainpage = "Coromon_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]

[en]
name = "Coromon"
icon = "coromonwiki.png"

[[en.origin]]
name = "Coromon Fandom Wiki"
url = "coromon.fandom.com"
mainpage = "Coromon_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Coromon Wiki"
host = "wiki.gg"
url = "coromon.wiki.gg"
platform = "mediawiki"
icon = "coromonwiki.png"
mainpage = "Coromon_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
