[en]
origins_label = "Cosmoteer Fandom Wiki"
destination = "Cosmoteer Wiki"
destination_base_url = "cosmoteer.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "cosmoteerwiki.png"
destination_main_page = "Cosmoteer_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Cosmoteer Fandom Wiki"
origin_base_url = "cosmoteer.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Cosmoteer_Wiki"
