[en]
name = "Cosmic Reach"
icon = "cosmicreachwiki.png"

[[en.origin]]
name = "Cosmic Reach Fandom Wiki"
url = "cosmicreach.fandom.com"
mainpage = "Cosmic_Reach_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Cosmic Reach Wiki"
host = "wiki.gg"
url = "cosmicreach.wiki.gg"
platform = "mediawiki"
icon = "cosmicreachwiki.png"
mainpage = "Cosmic_Reach_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
