[en]
name = "Cosmoteer"
icon = "cosmoteerwiki.png"

[[en.origin]]
name = "Cosmoteer Fandom Wiki"
url = "cosmoteer.fandom.com"
mainpage = "Cosmoteer_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Cosmoteer Wiki"
host = "wiki.gg"
url = "cosmoteer.wiki.gg"
platform = "mediawiki"
icon = "cosmoteerwiki.png"
mainpage = "Cosmoteer_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
