[en]
name = "Creatures"
icon = "creatureswiki.png"

[[en.origin]]
name = "Creatures Fandom Wiki"
url = "creatures.fandom.com"
mainpage = "Creatures_Wikia_Homepage"
content-path = "/wiki/"

[[en.destination]]
name = "Creatures Wiki"
url = "creatures.wiki"
platform = "mediawiki"
icon = "creatureswiki.png"
mainpage = "Creatures_Wiki_Homepage"
search-path = "/index.php"
content-path = "/"
tags = [
    "recommended",
]
