[en]
name = "Destiny 2 Minecraft"
icon = "d2mc.png"

[[en.origin]]
name = "D2MC Fandom Wiki"
url = "d2mc.fandom.com"
mainpage = "D2MC_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Destiny 2 Minecraft Edition Wiki"
host = "wiki.gg"
url = "d2mc.wiki.gg"
platform = "mediawiki"
icon = "d2mc.png"
mainpage = "Destiny_2_Minecraft_Edition_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
