[en]
origins_label = "Destiny 2 Minecraft Fandom Wiki"
destination = "Destiny 2 Minecraft Edition Wiki"
destination_base_url = "d2mc.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "d2mc.png"
destination_main_page = "Destiny_2_Minecraft_Edition_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "D2MC Fandom Wiki"
origin_base_url = "d2mc.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "D2MC_Wiki"
