[en]
origins_label = "Dark and Darker Fandom Wiki"
destination = "Dark and Darker Wiki"
destination_base_url = "darkanddarker.wiki.spellsandguns.com"
destination_platform = "mediawiki"
destination_icon = "darkanddarkerwiki.png"
destination_main_page = "Dark_and_Darker_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/"

[[en.origins]]
origin = "Dark and Darker Fandom Wiki"
origin_base_url = "dark-and-darker.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Dark_and_Darker_Wiki"
