[en]
origins_label = "Darkage Bizarre Fandom Wiki"
destination = "DarkGarden Studios Wiki"
destination_base_url = "darkgardenstudios.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "darkagebizarre.png"
destination_main_page = "DarkGarden_Studios_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[en.origins]]
origin = "Darkage Bizarre Fandom Wiki"
origin_base_url = "darkage-bizarre.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "DarkAge_Bizarre_Wiki"
