[en]
name = "Darkage Bizarre"
icon = "darkagebizarre.png"

[[en.origin]]
name = "Darkage Bizarre Fandom Wiki"
url = "darkage-bizarre.fandom.com"
mainpage = "DarkAge_Bizarre_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "DarkGarden Studios Wiki"
host = "wiki.gg"
url = "darkgardenstudios.wiki.gg"
platform = "mediawiki"
icon = "darkagebizarre.png"
mainpage = "DarkGarden_Studios_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
