[en]
name = "DashBored"
icon = "dashboredwiki.png"

[[en.origin]]
name = "DashBored Fandom Wiki"
url = "dashbored.fandom.com"
mainpage = "DashBored_Wikia"
content-path = "/wiki/"

[[en.destination]]
name = "DashBored Wiki"
host = "wiki.gg"
url = "dashbored.wiki.gg"
platform = "mediawiki"
icon = "dashboredwiki.png"
mainpage = "DashBored_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
