[en]
name = "Dead Estate"
icon = "deadestatewiki.png"

[[en.origin]]
name = "Dead Estate Fandom Wiki"
url = "deadestate.fandom.com"
mainpage = "Dead_Estate_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Dead Estate Wiki"
host = "wiki.gg"
url = "deadestate.wiki.gg"
platform = "mediawiki"
icon = "deadestatewiki.png"
mainpage = "Dead_Estate_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
