[en]
name = "Dead Cells"
icon = "deadcellswiki.png"

[[en.origin]]
name = "Dead Cells Fandom Wiki"
url = "deadcells.fandom.com"
mainpage = "Dead_Cells_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Dead Cells Wiki"
host = "wiki.gg"
url = "deadcells.wiki.gg"
platform = "mediawiki"
icon = "deadcellswiki.png"
mainpage = "Dead_Cells_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
