[en]
name = "Deadlock"
icon = "deadlock.png"

[[en.origin]]
name = "Deadlock Fandom Wiki"
url = "playdeadlock.fandom.com"
mainpage = "Deadlock_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Deadlock Wiki"
url = "deadlock.wiki"
platform = "mediawiki"
icon = "deadlock.png"
mainpage = "Deadlock_Wiki"
search-path = "/index.php"
content-path = "/"
tags = [
    "recommended",
]
