[en]
name = "Deltatraveler"
icon = "deltatravelerwiki.png"

[[en.origin]]
name = "Deltatraveler Fandom Wiki"
url = "deltatraveler.fandom.com"
mainpage = "The_Unofficial_Deltatraveler_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Deltatraveler Wiki"
host = "wiki.gg"
url = "deltatraveler.wiki.gg"
platform = "mediawiki"
icon = "deltatravelerwiki.png"
mainpage = "DELTATRAVELER"
search-path = "/index.php"
content-path = "/wiki/"
