[es]
name = "Deltarune"
icon = "deltarunewiki.png"

[[es.origin]]
name = "Deltarune Fandom Wiki"
url = "deltarune.fandom.com/es"
mainpage = "Wikia_Deltarune"
content-path = "/wiki/"

[[es.destination]]
name = "Deltarune Wiki"
url = "es.deltarune.wiki"
platform = "mediawiki"
icon = "deltarunewiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/w/"

[en]
name = "Deltarune"
icon = "deltarunewiki.png"

[[en.origin]]
name = "Deltarune Fandom Wiki"
url = "deltarune.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.origin]]
name = "Deltarune Fandom Wiki (Archived)"
url = "deltarune-archive.fandom.com"
mainpage = "Deltarune_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Deltarune Wiki"
url = "deltarune.wiki"
platform = "mediawiki"
icon = "deltarunewiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/w/"

[zh]
name = "Deltarune"
icon = "deltarunewiki.png"

[[zh.origin]]
name = "Deltarune Fandom Wiki"
url = "deltarune.fandom.com/zh"
mainpage = "Deltarune_Wiki"
content-path = "/wiki/"

[[zh.destination]]
name = "Deltarune Wiki"
url = "zh.deltarune.wiki"
platform = "mediawiki"
icon = "deltarunewiki.png"
mainpage = "Deltarune_Wiki"
search-path = "/index.php"
content-path = "/w/"
