[de]
name = "Detektiv Conan"
icon = "detektivconan.png"

[[de.origin]]
name = "Detektiv Conan Fandom Wiki"
url = "detektivconan.fandom.com"
mainpage = "Detektiv_Conan_Wiki"
content-path = "/wiki/"

[[de.destination]]
name = "ConanWiki"
url = "conanwiki.org"
platform = "mediawiki"
icon = "detektivconan.png"
mainpage = "Hauptseite"
search-path = "/index.php"
content-path = "/wiki/"
