[en]
name = "Detective Conan"
icon = "detectiveconan.png"

[[en.origin]]
name = "Detective Conan Fandom Wiki"
url = "detectiveconan.fandom.com"
mainpage = "Detective_Conan_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Detective Conan Wiki"
url = "www.detectiveconanworld.com"
platform = "mediawiki"
icon = "detectiveconan.png"
mainpage = "Main_Page"
search-path = "/wiki/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
