[en]
name = "Disfigure"
icon = "disfigure.png"

[[en.origin]]
name = "Disfigure Fandom Wiki"
url = "disfigure.fandom.com"
mainpage = "Disfigure_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Disfigure Wiki"
host = "wiki.gg"
url = "disfigure.wiki.gg"
platform = "mediawiki"
icon = "disfigure.png"
mainpage = "Disfigure_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
