[en]
name = "Doctor Who"
icon = "tardiswiki.png"

[[en.origin]]
name = "Tardis Fandom Wiki"
url = "tardis.fandom.com"
mainpage = "Doctor_Who_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Torchwood Archive Fandom Wiki"
url = "torchwood-archive.fandom.com"
mainpage = "Torchwood_Archive_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Doctor Who Neoseeker Wiki"
url = "doctorwho.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.origin]]
name = "The Sarah Jane Adventures Fandom Wiki"
url = "thesarahjaneadventures.fandom.com"
mainpage = "The_Sarah_Jane_Adventures_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Doctor Who Fandom Wiki"
url = "doctorwhotv.fandom.com"
mainpage = "Doctor_Who_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Doctor Who The Time Traveling Tardis Fandom Wiki"
url = "doctorwhothetimetravlingtardis.fandom.com"
mainpage = "Doctor_Who"
content-path = "/wiki/"

[[en.origin]]
name = "K9tv Fandom Wiki"
url = "k9tv.fandom.com"
mainpage = "K9tv_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Doctor Who Fandom Wiki"
url = "whoniverse.fandom.com"
mainpage = "Doctor_Who_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Dr Who Fandom Wiki"
url = "daleksrus.fandom.com"
mainpage = "Dr._Who_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Bigger on the Inside Fandom Wiki"
url = "biggerontheinside.fandom.com"
mainpage = "Bigger_on_the_Inside_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Tardis (Doctor Who) Wiki"
url = "tardis.wiki"
platform = "mediawiki"
icon = "tardiswiki.png"
mainpage = "Doctor_Who_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]

[zh]
name = "Doctor Who"
icon = "tardiswiki.png"

[[zh.origin]]
name = "Doctor Who Fandom Wiki"
url = "tardis.fandom.com/zh"
mainpage = "Tardis"
content-path = "/wiki/"

[[zh.destination]]
name = "Tardis (Doctor Who) Wiki"
url = "zh.tardis.wiki"
platform = "mediawiki"
icon = "tardiswiki.png"
mainpage = "Tardis百科"
search-path = "/index.php"
content-path = "/"
tags = [
    "recommended",
]
