[fr]
name = "Dofus"
icon = "dofuswiki.png"

[[fr.origin]]
name = "Dofus Fandom Wiki"
url = "dofuswiki.fandom.com/fr"
mainpage = "Wiki_Dofus"
content-path = "/wiki/"

[[fr.destination]]
name = "Dofus Wiki"
url = "wiki-dofus.eu"
platform = "mediawiki"
icon = "dofuswiki.png"
mainpage = "Accueil"
search-path = "/w"
content-path = "/w/"
tags = [
    "recommended",
]
