[en]
name = "Cyberdog Nation Server"
icon = "dogcraftwiki.png"

[[en.origin]]
name = "Cyberdog Nation Server Fandom Wiki"
url = "dogcraft.fandom.com"
mainpage = "Cyberdog_Nation_Server_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Dogcraft Wiki"
url = "dogcraft.net"
platform = "mediawiki"
icon = "dogcraftwiki.png"
mainpage = "Main_Page"
search-path = "/wiki/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
