[en]
name = "Dome Keeper"
icon = "domekeeperwiki.png"

[[en.origin]]
name = "Dome Keeper Fandom Wiki"
url = "dome-keeper.fandom.com"
mainpage = "Dome_Keeper_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Dome Keeper Wiki"
host = "wiki.gg"
url = "domekeeper.wiki.gg"
platform = "mediawiki"
icon = "domekeeperwiki.png"
mainpage = "Dome_Keeper_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
