[en]
name = "Don't Starve"
icon = "dontstarvewiki.png"

[[en.origin]]
name = "Don't Starve Fandom Wiki"
url = "dontstarve.fandom.com"
mainpage = "Don't_Starve_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Don't Starve Wiki"
host = "wiki.gg"
url = "dontstarve.wiki.gg"
platform = "mediawiki"
icon = "dontstarvewiki.png"
mainpage = "Don't_Starve_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]

[fr]
name = "Don't Starve"
icon = "dontstarvewiki.png"

[[fr.origin]]
name = "Don't Starve Fandom Wiki"
url = "dont-starve.fandom.com/fr"
mainpage = "Wiki_Don't_starve"
content-path = "/wiki/"

[[fr.destination]]
name = "Don't Starve Wiki"
host = "wiki.gg"
url = "dontstarve.wiki.gg/fr"
platform = "mediawiki"
icon = "dontstarvewiki.png"
mainpage = "Wiki_Don't_starve"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
