[en]
name = "Doom"
icon = "doomwiki.png"

[[en.origin]]
name = "Doom Fandom Wiki"
url = "doom.fandom.com"
mainpage = "Doom_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Doom Wiki - Neoseeker"
url = "doom.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "The Doom Wiki"
url = "doomwiki.org"
platform = "mediawiki"
icon = "doomwiki.png"
mainpage = "Entryway"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
