[en]
name = "Dota 2"
icon = "liquipediadota2wiki.png"

[[en.origin]]
name = "Dota 2 Fandom Wiki"
url = "dota2.fandom.com"
mainpage = "Dota_2_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Liquipedia Dota 2 Wiki"
url = "liquipedia.net/dota2"
platform = "mediawiki"
icon = "liquipediadota2wiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/"
