[en]
name = "Dovedale Railway"
icon = "dovedalerailwaywiki.png"

[[en.origin]]
name = "Dovedale Railway Fandom Wiki"
url = "dovedale.fandom.com"
mainpage = "Dovedale_Railway_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Dovedale Railway Wiki"
url = "dovedale.wiki"
platform = "mediawiki"
icon = "dovedalerailwaywiki.png"
mainpage = "Dovedale_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
