[en]
name = "Dragalia Lost"
icon = "dragalialost.png"

[[en.origin]]
name = "Dragalia Lost Fandom Wiki"
url = "dragalialost.fandom.com"
mainpage = "Dragalia_Lost_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Dragalia Lost Wiki"
url = "dragalialost.wiki"
platform = "mediawiki"
icon = "dragalialost.png"
mainpage = "Dragalia_Lost_Wiki"
search-path = "/index.php"
content-path = "/w/"
