[en]
name = "Drawn to Life"
icon = "wapopedia.png"

[[en.origin]]
name = "Drawn to Life Fandom Wiki"
url = "drawntolife.fandom.com"
mainpage = "Drawn_to_Life_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Wapopedia"
url = "drawntolife.wiki"
platform = "mediawiki"
icon = "wapopedia.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/en/"
