[en]
name = "Dreamlight Valley"
icon = "dreamlightvalleywiki.png"

[[en.origin]]
name = "Dreamlight Valley Fandom Wiki"
url = "disneydreamlightvalley.fandom.com"
mainpage = "Disney_Dreamlight_Valley_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Dreamlight Valley Fandom Wiki"
url = "disney-dreamlight-valley.fandom.com"
mainpage = "Disney_Dreamlight_Valley_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Dreamlight Valley Wiki"
url = "dreamlightvalleywiki.com"
platform = "mediawiki"
icon = "dreamlightvalleywiki.png"
mainpage = "Dreamlight_Valley_Wiki"
search-path = "/index.php"
content-path = "/"
