[en]
name = "Dreamsphere"
icon = "dreamsphere.png"

[[en.origin]]
name = "Dreamsphere Fandom Wiki"
url = "dreamsphere.fandom.com"
mainpage = "Dreamsphere_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Dreamsphere Wiki"
host = "Miraheze"
url = "dreamsphere.miraheze.org"
platform = "mediawiki"
icon = "dreamsphere.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
