[en]
name = "DREDGE"
icon = "dredgewiki.png"

[[en.origin]]
name = "DREDGE Fandom Wiki"
url = "dredge.fandom.com"
mainpage = "DREDGE_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "DREDGE Wiki"
host = "wiki.gg"
url = "dredge.wiki.gg"
platform = "mediawiki"
icon = "dredgewiki.png"
mainpage = "DREDGE_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
