[en]
name = "Dungeons and Degenerate Gamblers"
icon = "dndg.png"

[[en.origin]]
name = "Dungeons and Degenerate Gamblers Fandom Wiki"
url = "dungeons-and-degenerate-gamblers.fandom.com"
mainpage = "Dungeons_and_Degenerate_Gamblers_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Dungeons and Degenerate Gamblers Wiki"
host = "Miraheze"
url = "degenerategamblers.miraheze.org"
platform = "mediawiki"
icon = "dndg.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
