[en]
name = "Dungeon Defenders II"
icon = "dungeondefenders2wiki.png"

[[en.origin]]
name = "Dungeon Defenders II Fandom Wiki"
url = "dungeondefenders2.fandom.com"
mainpage = "Dungeon_Defenders_II_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Dungeon Defenders 2 Wiki"
url = "wiki.dungeondefenders2.com"
platform = "mediawiki"
icon = "dungeondefenders2wiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
