[en]
name = "Dying Light"
icon = "dyinglightwiki.png"

[[en.origin]]
name = "Dying Light Fandom Wiki"
url = "dyinglight.fandom.com"
mainpage = "Dying_Light_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Dying Light Wiki"
host = "wiki.gg"
url = "dyinglight.wiki.gg"
platform = "mediawiki"
icon = "dyinglightwiki.png"
mainpage = "Dying_Light_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
