[en]
name = "Dyson Sphere Program"
icon = "dspwiki.png"

[[en.origin]]
name = "Dyson Sphere Program Fandom Wiki"
url = "dyson-sphere-program.fandom.com"
mainpage = "Dyson_Sphere_Program_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Dyson Sphere Program Wiki"
url = "dsp-wiki.com"
platform = "mediawiki"
icon = "dspwiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/"
