[en]
origins_label = "EarthBound Fandom & Neoseeker Wikis"
destination = "WikiBound"
destination_base_url = "wikibound.info"
destination_platform = "mediawiki"
destination_icon = "wikibound.png"
destination_main_page = "WikiBound"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"

[[en.origins]]
origin = "EarthBound Fandom Wiki"
origin_base_url = "earthbound.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Main_Page"

[[en.origins]]
origin = "Mother Wiki - Neoseeker"
origin_base_url = "mother.neoseeker.com"
origin_content_path = "/wiki/"
origin_main_page = "Main_Page"

[it]
origins_label = "EarthBound Fandom Wiki"
destination = "WikiBound"
destination_base_url = "it.wikibound.info"
destination_platform = "mediawiki"
destination_icon = "wikibound.png"
destination_main_page = "Pagina_principale"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"

[[it.origins]]
origin = "EarthBound Fandom Wiki"
origin_base_url = "earthbound.fandom.com/it"
origin_content_path = "/wiki/"
origin_main_page = "EarthBound_Wiki"
