[en]
name = "Eastward"
icon = "eastwardwiki.png"

[[en.origin]]
name = "Eastward Fandom Wiki"
url = "eastward.fandom.com"
mainpage = "Eastward_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Eastward Wiki"
url = "eastwardwiki.com"
platform = "mediawiki"
icon = "eastwardwiki.png"
mainpage = "Eastward_Wiki"
search-path = "/mediawiki/index.php"
content-path = "/"
tags = [
    "recommended",
]
