[en]
origins_label = "Eiyuden Chronicle: Hundred Heroes Fandom Wiki"
destination = "Eiyuden Chronicle Wiki"
destination_base_url = "eiyuden.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "eiyudenchroniclewiki.png"
destination_main_page = "Eiyuden_Chronicle_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[en.origins]]
origin = "Eiyuden Chronicle: Hundred Heroes Fandom Wiki"
origin_base_url = "eiyuden-chronicle-hundred-heroes.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Eiyuden_Chronicle:_Hundred_Heroes_Wiki"
