[en]
name = "Elden Ring"
icon = "eldenring.png"

[[en.origin]]
name = "Elden Ring Fandom Wiki"
url = "eldenring.fandom.com"
mainpage = "Elden_Ring_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Elden Ring Fextralife Wiki"
url = "eldenring.wiki.fextralife.com"
mainpage = "Elden Ring Wiki"
content-path = "/"

[[en.destination]]
name = "Eldenpedia"
host = "wiki.gg"
url = "eldenring.wiki.gg"
platform = "mediawiki"
icon = "eldenring.png"
mainpage = "Eldenpedia"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
