[en]
name = "Ember Knights"
icon = "emberknightswiki.png"

[[en.origin]]
name = "Ember Knights Fandom Wiki"
url = "ember-knights-game.fandom.com"
mainpage = "Ember_Knights_-_Game_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Ember Knights Wiki"
host = "wiki.gg"
url = "emberknights.wiki.gg"
platform = "mediawiki"
icon = "emberknightswiki.png"
mainpage = "Ember_Knights_-_Game_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
