[en]
name = "Empire of Sin"
icon = "empireofsin.png"

[[en.origin]]
name = "EmpireOfSin Fandom Wiki"
url = "empireofsin.fandom.com"
mainpage = "EmpireOfSin_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Empire of Sin Wiki"
host = "Paradox"
url = "eos.paradoxwikis.com"
platform = "mediawiki"
icon = "empireofsin.png"
mainpage = "Empire_of_Sin_Wiki"
search-path = "/index.php"
content-path = "/"
tags = [
    "official",
    "recommended",
]
