[en]
name = "Endless Legend"
icon = "endlesslegendwiki.png"

[[en.origin]]
name = "Endless Legend Fandom Wiki"
url = "endlesslegend.fandom.com"
mainpage = "Endless_Legend_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Endless Legend Wiki"
host = "wiki.gg"
url = "endlesslegend.wiki.gg"
platform = "mediawiki"
icon = "endlesslegendwiki.png"
mainpage = "Endless_Legend_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
