[en]
name = "Enshrouded"
icon = "enshroudedwiki.png"

[[en.origin]]
name = "Enshrouded Fandom Wiki"
url = "enshrouded.fandom.com"
mainpage = "Enshrouded_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Enshrouded Wiki"
host = "wiki.gg"
url = "enshrouded.wiki.gg"
platform = "mediawiki"
icon = "enshroudedwiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
