[en]
name = "Essentials Docs"
icon = "essentialsenginewiki.png"

[[en.origin]]
name = "Essentials Docs Fandom Wiki"
url = "essentialsdocs.fandom.com"
mainpage = "Essentials_Docs_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Essentials Engine Wiki"
host = "Miraheze"
url = "essentialsengine.miraheze.org"
platform = "mediawiki"
icon = "essentialsenginewiki.png"
mainpage = "Essentials_Engine_wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
