[en]
origins_label = "Evangelion Fandom & Neoseeker Wikis"
destination = "EvaWiki"
destination_base_url = "wiki.evageeks.org"
destination_platform = "mediawiki"
destination_icon = "evawiki.png"
destination_main_page = "Main_Page"
destination_search_path = "/index.php"
destination_content_path = "/"

[[en.origins]]
origin = "Evangelion Fandom Wiki"
origin_base_url = "evangelion.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Main_Page"

[[en.origins]]
origin = "Neon Genesis Evangelion Wiki - Neoseeker"
origin_base_url = "evangelion.neoseeker.com"
origin_content_path = "/wiki/"
origin_main_page = "Main_Page"

[fr]
origins_label = "Evangelion Fandom Wiki"
destination = "Shin Wiki Evangelion"
destination_base_url = "shinwikievangelionfr.miraheze.org"
destination_platform = "mediawiki"
destination_icon = "shinwikievagelion.png"
destination_main_page = "Wiki_Evangelion"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "Miraheze"

[[fr.origins]]
origin = "Evangelion Fandom Wiki"
origin_base_url = "evangelion.fandom.com/fr"
origin_content_path = "/wiki/"
origin_main_page = "Wiki_Evangelion"
