[en]
name = "EVE Online"
icon = "eveonline.png"

[[en.origin]]
name = "EVE Fandom Wiki"
url = "eve.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "EVE University Wiki"
url = "wiki.eveuniversity.org"
platform = "mediawiki"
icon = "eveonline.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/"
tags = [
    "recommended",
]
