[en]
origins_label = "Everything Upgrade Tree Fandom Wiki"
destination = "Everything Upgrade Tree Wiki"
destination_base_url = "eutwiki.com"
destination_platform = "mediawiki"
destination_icon = "everythingupgradetree.png"
destination_main_page = ""
destination_search_path = "/w/index.php"
destination_content_path = "/"
destination_host = "Miraheze"
tags = [
    "official",
]

[[en.origins]]
origin = "Everything Upgrade Tree Fandom Wiki"
origin_base_url = "everything-upgrade-tree.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Everything_Upgrade_Tree_Wiki"
