[en]
name = "Everything Upgrade Tree"
icon = "everythingupgradetree.png"

[[en.origin]]
name = "Everything Upgrade Tree Fandom Wiki"
url = "everything-upgrade-tree.fandom.com"
mainpage = "Everything_Upgrade_Tree_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Everything Upgrade Tree Wiki"
host = "Miraheze"
url = "eutwiki.com"
platform = "mediawiki"
icon = "everythingupgradetree.png"
mainpage = ""
search-path = "/w/index.php"
content-path = "/"
tags = [
    "official",
]
