[en]
name = "Falcom"
icon = "falcomwiki.png"

[[en.origin]]
name = "Kiseki Fandom Wiki"
url = "kiseki.fandom.com"
mainpage = ""
content-path = "/wiki/"

[[en.origin]]
name = "Ys Fandom Wiki"
url = "isu.fandom.com"
mainpage = "Ys_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Tokyo Xanadu Fandom Wiki"
url = "tokyoxanadu.fandom.com"
mainpage = "Tokyo_Xanadu_Wikia"
content-path = "/wiki/"

[[en.origin]]
name = "Gagharv Fandom Wiki"
url = "gagharv.fandom.com"
mainpage = "Gagharv_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Falcomverse Fandom Wiki"
url = "nihon-falcom.fandom.com"
mainpage = "The_Legend_Of_Heroes"
content-path = "/wiki/"

[[en.origin]]
name = "Gurumin Fandom Wiki"
url = "gurumin.fandom.com"
mainpage = "Gurumin_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Falcom Wiki"
host = "Miraheze"
url = "falcom.wiki"
platform = "mediawiki"
icon = "falcomwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
