[en]
name = "Fallen Aces"
icon = "fallenaceswiki.png"

[[en.origin]]
name = "Fallen Aces Fandom Wiki"
url = "fallen-aces.fandom.com"
mainpage = "Fallen_Aces_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Fallen Aces Wiki"
host = "wiki.gg"
url = "fallenaces.wiki.gg"
platform = "mediawiki"
icon = "fallenaceswiki.png"
mainpage = "Fallen_Aces_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
