[en]
name = "Fallout"
icon = "fallout.png"

[[en.origin]]
name = "Fallout Fandom Wiki (Nukapedia)"
url = "fallout.fandom.com"
mainpage = "Fallout_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Fallout Fandom Wiki (Archived)"
url = "fallout-archive.fandom.com"
mainpage = "The_Vault_Fallout_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Fallout Wiki - Neoseeker"
url = "fallout.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.origin]]
name = "Fallout 4 Fextralife Wiki"
url = "fallout4.wiki.fextralife.com"
mainpage = "Fallout 4 Wiki"
content-path = "/"

[[en.origin]]
name = "Fallout 76 Fextralife Wiki"
url = "fallout76.wiki.fextralife.com"
mainpage = "Fallout 76 Wiki"
content-path = "/"

[[en.destination]]
name = "Independent Fallout Wiki"
url = "fallout.wiki"
platform = "mediawiki"
icon = "fallout.png"
mainpage = "Fallout_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]

[fr]
name = "L'Abri Fallout"
icon = "lesarchivesdevaulttec.png"

[[fr.origin]]
name = "L'Abri Fallout Fandom Wiki"
url = "fallout.fandom.com/fr"
mainpage = "Accueil"
content-path = "/wiki/"

[[fr.destination]]
name = "Les Archives de Vault-Tec"
url = "fallout-wiki.com"
platform = "mediawiki"
icon = "lesarchivesdevaulttec.png"
mainpage = "Accueil"
search-path = "/index.php"
content-path = "/"
tags = [
    "recommended",
]
