[en]
origins_label = "Famicom Fandom Wiki"
destination = "FamiWiki"
destination_base_url = "famiwiki.net"
destination_platform = "mediawiki"
destination_icon = "famiwiki.png"
destination_main_page = "Main_Page"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"

[[en.origins]]
origin = "Famicom Fandom Wiki"
origin_base_url = "famicom.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Famicom_Wiki"
