[en]
name = "Final Fantasy XIV"
icon = "ffxiv.png"

[[en.origin]]
name = "Final Fantasy XIV Fandom Wiki"
url = "ffxiv.fandom.com"
mainpage = "Final_Fantasy_XIV:_A_Realm_Reborn_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Final Fantasy XIV Online Wiki"
url = "ffxiv.consolegameswiki.com"
platform = "mediawiki"
icon = "ffxiv.png"
mainpage = "FF14_Wiki"
search-path = "/mediawiki/index.php"
content-path = "/wiki/"
