[en]
name = "Find The Markers"
icon = "findthemarkerswiki.png"

[[en.origin]]
name = "Find The Markers Fandom Wiki"
url = "find-the-markers-roblox.fandom.com"
mainpage = "Find_The_Markers_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Find The Markers Wiki"
host = "Miraheze"
url = "findthemarkers.miraheze.org"
platform = "mediawiki"
icon = "findthemarkerswiki.png"
mainpage = "Find_The_Markers_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
