[en]
name = "Find Everything"
icon = "findeverythingwiki.png"

[[en.origin]]
name = "Find Everything Fandom Wiki"
url = "find-everything-rbx.fandom.com"
mainpage = "Find_Everything_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Find Everything Wiki"
host = "Miraheze"
url = "findeverything.miraheze.org"
platform = "mediawiki"
icon = "findeverythingwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
