[en]
name = "Fisch"
icon = "officialfischwiki.png"

[[en.origin]]
name = "Fisch Fandom Wiki"
url = "fisch.fandom.com"
mainpage = "Fisch_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Fisch Wiki"
host = "Miraheze"
url = "fischipedia.org"
platform = "mediawiki"
icon = "officialfischwiki.png"
mainpage = "Fisch_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
