[fr]
name = "Forge of Empires"
icon = "forgeofempires.png"

[[fr.origin]]
name = "Forge of Empires Fandom Wiki"
url = "forgeofempires.fandom.com/fr"
mainpage = "Forge_of_Empires_Wiki"
content-path = "/wiki/"

[[fr.destination]]
name = "Forge of Empires Wiki"
url = "fr.wiki.forgeofempires.com"
platform = "mediawiki"
icon = "forgeofempires.png"
mainpage = "Accueil"
search-path = "/index.php"
content-path = "/index.php?title="
tags = [
    "official",
    "recommended",
]
