[en]
name = "Foxhole"
icon = "foxholewiki.png"

[[en.origin]]
name = "Foxhole Fandom Wiki"
url = "foxhole.fandom.com"
mainpage = "Foxhole_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Foxhole Wiki"
host = "wiki.gg"
url = "foxhole.wiki.gg"
platform = "mediawiki"
icon = "foxholewiki.png"
mainpage = "Foxhole_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
