[en]
name = "FrackinUniverse"
icon = "frackinuniversewiki.png"

[[en.origin]]
name = "FrackinUniverse Fandom Wiki"
url = "frackinuniverse.fandom.com"
mainpage = "FrackinUniverse_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Frackin' Universe Wiki"
host = "Miraheze"
url = "frackinuniverse.miraheze.org"
platform = "mediawiki"
icon = "frackinuniversewiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
