[en]
name = "Friday Night Funkin'"
icon = "fridaynightfunkinwiki.png"

[[en.origin]]
name = "Friday Night Funkin' Fandom Wiki"
url = "fridaynightfunkin.fandom.com"
mainpage = "Friday_Night_Funkin'_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Friday Night Funkin Wiki"
host = "wiki.gg"
url = "fridaynightfunkin.wiki.gg"
platform = "mediawiki"
icon = "fridaynightfunkinwiki.png"
mainpage = "Friday_Night_Funkin'_Wiki"
search-path = "/index.php"
content-path = "/wiki/"

[ja]
name = "Friday Night Funkin'"
icon = "fridaynightfunkinwiki.png"

[[ja.origin]]
name = "Friday Night Funkin' Fandom Wiki"
url = "fridaynightfunkin.fandom.com/ja"
mainpage = "Friday_Night_Funkin'_Wiki"
content-path = "/wiki/"

[[ja.destination]]
name = "Friday Night Funkin Wiki"
host = "wiki.gg"
url = "fridaynightfunkin.wiki.gg/ja"
platform = "mediawiki"
icon = "fridaynightfunkinwiki.png"
mainpage = "Friday_Night_Funkin'_Wiki"
search-path = "/index.php"
content-path = "/wiki/"

[zh]
name = "Friday Night Funkin'"
icon = "fridaynightfunkinwiki.png"

[[zh.origin]]
name = "Friday Night Funkin' Fandom Wiki"
url = "fridaynightfunkin.fandom.com/zh"
mainpage = "Friday_Night_Funkin'_Wiki"
content-path = "/wiki/"

[[zh.destination]]
name = "Friday Night Funkin Wiki"
host = "wiki.gg"
url = "fridaynightfunkin.wiki.gg/zh"
platform = "mediawiki"
icon = "fridaynightfunkinwiki.png"
mainpage = "Friday_Night_Funkin'_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
