[en]
origins_label = "Friends at the Table Fandom Wikis"
destination = "FatTWiki"
destination_base_url = "fatt.wiki"
destination_platform = "mediawiki"
destination_icon = "friendsatthetable.png"
destination_main_page = "Main_Page"
destination_search_path = "/wiki/index.php"
destination_content_path = "/view/"

[[en.origins]]
origin = "Friends at the Table Fandom Wiki"
origin_base_url = "friendsatthetable.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Friends_at_the_Table_Wikia"

[[en.origins]]
origin = "The New Archives Fandom Wiki"
origin_base_url = "thenewarchives.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "The_New_Archives_Wikia"

[[en.origins]]
origin = "COUNTER/Weight Fandom Wiki"
origin_base_url = "counterweight.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "COUNTER/Weight_Wikia"

[[en.origins]]
origin = "Twilight Mirage Fandom Wiki"
origin_base_url = "twilightmirage.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Twilight_Mirage_Wiki"

[[en.origins]]
origin = "PARTIZAN Fandom Wiki"
origin_base_url = "partizan.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "PARTIZAN_Wiki"

[[en.origins]]
origin = "Sangfielle Fandom Wiki"
origin_base_url = "sangfielle.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Sangfielle_Wiki"

[[en.origins]]
origin = "Bluff City Fandom Wiki"
origin_base_url = "visit-bluff-city.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Bluff_City_Wiki"
