[en]
name = "Friends at the Table"
icon = "friendsatthetable.png"

[[en.origin]]
name = "Friends at the Table Fandom Wiki"
url = "friendsatthetable.fandom.com"
mainpage = "Friends_at_the_Table_Wikia"
content-path = "/wiki/"

[[en.origin]]
name = "The New Archives Fandom Wiki"
url = "thenewarchives.fandom.com"
mainpage = "The_New_Archives_Wikia"
content-path = "/wiki/"

[[en.origin]]
name = "COUNTER/Weight Fandom Wiki"
url = "counterweight.fandom.com"
mainpage = "COUNTER/Weight_Wikia"
content-path = "/wiki/"

[[en.origin]]
name = "Twilight Mirage Fandom Wiki"
url = "twilightmirage.fandom.com"
mainpage = "Twilight_Mirage_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "PARTIZAN Fandom Wiki"
url = "partizan.fandom.com"
mainpage = "PARTIZAN_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Sangfielle Fandom Wiki"
url = "sangfielle.fandom.com"
mainpage = "Sangfielle_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Bluff City Fandom Wiki"
url = "visit-bluff-city.fandom.com"
mainpage = "Bluff_City_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "FatTWiki"
url = "fatt.wiki"
platform = "mediawiki"
icon = "friendsatthetable.png"
mainpage = "Main_Page"
search-path = "/wiki/index.php"
content-path = "/view/"
