[en]
name = "fromARGONAVIS"
icon = "fromargonaviswiki.png"

[[en.origin]]
name = "fromARGONAVIS Fandom Wiki"
url = "argo-bdp.fandom.com"
mainpage = "ARGONAVIS_from_BanG_Dream!_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "from ARGONAVIS Wiki"
host = "Miraheze"
url = "argobdp.miraheze.org"
platform = "mediawiki"
icon = "fromargonaviswiki.png"
mainpage = "from_ARGONAVIS_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
