[en]
name = "Futurama"
icon = "infosphere.png"

[[en.origin]]
name = "Futurama Fandom Wiki"
url = "futurama.fandom.com"
mainpage = "Futurama_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Futurama Wiki - Neoseeker"
url = "futurama.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "The Infosphere"
url = "theinfosphere.org"
platform = "mediawiki"
icon = "infosphere.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/"
tags = [
    "recommended",
]
