[en]
name = "F-Zero"
icon = "fzero.png"

[[en.origin]]
name = "F-Zero Fandom Wiki"
url = "fzero.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.origin]]
name = "F-Zero Wiki - Neoseeker"
url = "fzero.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "F-Zero Wiki"
url = "mutecity.org"
platform = "mediawiki"
icon = "fzero.png"
mainpage = "F-Zero_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
