[en]
origins_label = "F-Zero Fandom & Neoseeker Wikis"
destination = "F-Zero Wiki"
destination_base_url = "mutecity.org"
destination_platform = "mediawiki"
destination_icon = "fzero.png"
destination_main_page = "F-Zero_Wiki"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"

[[en.origins]]
origin = "F-Zero Fandom Wiki"
origin_base_url = "fzero.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Main_Page"

[[en.origins]]
origin = "F-Zero Wiki - Neoseeker"
origin_base_url = "fzero.neoseeker.com"
origin_content_path = "/wiki/"
origin_main_page = "Main_Page"
