[en]
name = "Galaxy Life"
icon = "galaxylifewiki.png"

[[en.origin]]
name = "Galaxy Life Fandom Wiki"
url = "galaxylife.fandom.com"
mainpage = "Galaxy_Life_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Galaxy Life Wiki"
host = "wiki.gg"
url = "galaxylife.wiki.gg"
platform = "mediawiki"
icon = "galaxylifewiki.png"
mainpage = "Galaxy_Life_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
