[en]
name = "Geometry Dash"
icon = "geometrydashwiki.png"

[[en.origin]]
name = "Geometry Dash Fandom Wiki"
url = "geometry-dash.fandom.com"
mainpage = "Geometry_Dash_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Geometry Dash Fan Fandom Wiki"
url = "geometry-dash-fan.fandom.com"
mainpage = "Geometry_Dash_Fan_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Geometry Dash Wiki"
host = "wiki.gg"
url = "geometrydash.wiki.gg"
platform = "mediawiki"
icon = "geometrydashwiki.png"
mainpage = "Geometry_Dash_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
