[en]
origins_label = "Geometry Dash Fandom Wikis"
destination = "Geometry Dash Wiki"
destination_base_url = "geometrydash.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "geometrydashwiki.png"
destination_main_page = "Geometry_Dash_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Geometry Dash Fandom Wiki"
origin_base_url = "geometry-dash.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Geometry_Dash_Wiki"

[[en.origins]]
origin = "Geometry Dash Fan Fandom Wiki"
origin_base_url = "geometry-dash-fan.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Geometry_Dash_Fan_Wiki"
