[en]
name = "Giana Sisters"
icon = "gianapedia.png"

[[en.origin]]
name = "Giana Sisters Fandom Wiki"
url = "giana-sisters.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "GianaPedia"
host = "Miraheze"
url = "gianasisters.miraheze.org"
platform = "mediawiki"
icon = "gianapedia.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
