[en]
name = "Gigantic"
icon = "giganticwiki.png"

[[en.origin]]
name = "Gigantic Fandom Wiki"
url = "gigantic.fandom.com"
mainpage = "Gigantic_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Gigantic Fandom Wiki (Archived)"
url = "gigantic-archive.fandom.com"
mainpage = "Gigantic_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Gigantic Wiki"
host = "Miraheze"
url = "gogigantic.miraheze.org"
platform = "mediawiki"
icon = "giganticwiki.png"
mainpage = "Gigantic_Wiki:Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
