[en]
name = "GFL Universe's"
icon = "iopwiki.png"

[[en.origin]]
name = "GFL Universe's Fandom Wiki"
url = "girls-frontline.fandom.com"
mainpage = "GFL_Universe_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "IOP Wiki"
url = "iopwiki.com"
platform = "mediawiki"
icon = "iopwiki.png"
mainpage = "IOP_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
