[en]
name = "(the) Gnorp Apologue"
icon = "gnorp.png"

[[en.origin]]
name = "(the) Gnorp Apologue Fandom Wiki"
url = "gnorp-apologue.fandom.com"
mainpage = "(the)_Gnorp_Apologue_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "(the) Gnorp Apologue Wiki"
host = "wiki.gg"
url = "gnorp.wiki.gg"
platform = "mediawiki"
icon = "gnorp.png"
mainpage = "(the)_Gnorp_Apologue_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
