[en]
name = "Godzilla"
icon = "wikizilla.png"

[[en.origin]]
name = "Godzilla Fandom Wiki"
url = "godzilla.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Wikizilla"
url = "wikizilla.org"
platform = "mediawiki"
icon = "wikizilla.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
