[en]
name = "Gothic"
icon = "gothicwiki.png"

[[en.origin]]
name = "Gothic Fandom Wiki"
url = "gothic.fandom.com"
mainpage = "Gothic_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Gothic Wiki"
url = "gothic.wiki"
platform = "mediawiki"
icon = "gothicwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/w/"
