[en]
origins_label = "Gothic Fandom Wiki"
destination = "Gothic Wiki"
destination_base_url = "gothic.wiki"
destination_platform = "mediawiki"
destination_icon = "gothicwiki.png"
destination_main_page = "Main_Page"
destination_search_path = "/w/index.php"
destination_content_path = "/w/"

[[en.origins]]
origin = "Gothic Fandom Wiki"
origin_base_url = "gothic.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Gothic_Wiki"
