[en]
name = "GraalMilitary"
icon = "graalmilitarywiki.png"

[[en.origin]]
name = "GraalMilitary Fandom Wiki"
url = "graalmilitary.fandom.com"
mainpage = "GraalMilitary_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Graal Military Wiki"
host = "Miraheze"
url = "wiki.graalmilitary.com"
platform = "mediawiki"
icon = "graalmilitarywiki.png"
mainpage = "GraalMilitary_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
