[en]
name = "Green Day"
icon = "greendaywiki.png"

[[en.origin]]
name = "Green Day Fandom Wiki"
url = "greenday.fandom.com"
mainpage = "Green_Day_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Green Day Wiki"
host = "ShoutWiki"
url = "greenday.shoutwiki.com"
platform = "mediawiki"
icon = "greendaywiki.png"
mainpage = "Green_Day_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
