[fr]
name = "Grepolis"
icon = "grepolis.png"

[[fr.origin]]
name = "Grepolis Fandom Wiki"
url = "grepolis.fandom.com/fr"
mainpage = "Wiki_Grepolis"
content-path = "/wiki/"

[[fr.destination]]
name = "Grepolis Wiki"
url = "wiki.fr.grepolis.com"
platform = "mediawiki"
icon = "grepolis.png"
mainpage = "Accueil"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
