[en]
name = "Grounded"
icon = "groundedwiki.png"

[[en.origin]]
name = "Grounded Fandom Wiki"
url = "grounded.fandom.com"
mainpage = "Grounded_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Grounded Wiki"
host = "wiki.gg"
url = "grounded.wiki.gg"
platform = "mediawiki"
icon = "groundedwiki.png"
mainpage = "Grounded_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
