[en]
name = "GTA"
icon = "gtawiki.png"

[[en.origin]]
name = "GTA Fandom Wiki"
url = "gta.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "GTA Wiki"
url = "gta.wiki"
platform = "mediawiki"
icon = "gtawiki.png"
mainpage = "Main_Page"
search-path = "/"
content-path = "/w/"
