[en]
name = "GTFO"
icon = "gtfowiki.png"

[[en.origin]]
name = "GTFO Fandom Wiki"
url = "gtfo.fandom.com"
mainpage = "GTFO_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "GTFO Wiki"
host = "wiki.gg"
url = "gtfo.wiki.gg"
platform = "mediawiki"
icon = "gtfowiki.png"
mainpage = "GTFO_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
