[en]
name = "Guilty Gear"
icon = "guiltygearwiki.png"

[[en.origin]]
name = "Guilty Gear Fandom Wiki"
url = "guiltygear.fandom.com"
mainpage = "Guilty_Gear_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Guilty Gear Wiki"
host = "wiki.gg"
url = "guiltygear.wiki.gg"
platform = "mediawiki"
icon = "guiltygearwiki.png"
mainpage = "Guilty_Gear_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
