[ru]
name = "Half-Life"
icon = "combine.png"

[[ru.origin]]
name = "Half-Life Fandom Wiki"
url = "halflife.fandom.com/ru"
mainpage = "Заглавная_страница"
content-path = "/wiki/"

[[ru.destination]]
name = "Combine OverWiki"
url = "combineoverwiki.net"
platform = "mediawiki"
icon = "combine.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
content-suffix = "/ru"

[es]
name = "Half-Life & Portal"
icon = "combine.png"

[[es.origin]]
name = "Half-Life & Portal Fandom Wiki"
url = "halflife.fandom.com/es"
mainpage = "Portada"
content-path = "/wiki/"

[[es.destination]]
name = "Combine OverWiki"
url = "combineoverwiki.net"
platform = "mediawiki"
icon = "combine.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
content-suffix = "/es"

[en]
name = "Half-Life"
icon = "combine.png"

[[en.origin]]
name = "Half-Life & Portal Fandom Wiki"
url = "half-life.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.origin]]
name = "Half-Life Wiki - Neoseeker"
url = "halflife.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Combine OverWiki"
url = "combineoverwiki.net"
platform = "mediawiki"
icon = "combine.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"

[pl]
name = "Half-Life"
icon = "combine.png"

[[pl.origin]]
name = "Half-Life Fandom Wiki"
url = "half-life.fandom.com/pl"
mainpage = "Half-Life_Wiki"
content-path = "/wiki/"

[[pl.destination]]
name = "Combine OverWiki"
url = "combineoverwiki.net"
platform = "mediawiki"
icon = "combine.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
content-suffix = "/pl"

[zh]
name = "Half-Life"
icon = "combine.png"

[[zh.origin]]
name = "Half-Life Fandom Wiki"
url = "hlforever.fandom.com"
mainpage = "首頁"
content-path = "/wiki/"

[[zh.destination]]
name = "Combine OverWiki"
url = "combineoverwiki.net"
platform = "mediawiki"
icon = "combine.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
content-suffix = "/zh-hans"
