[en]
name = "Halo"
icon = "halopedia.png"

[[en.origin]]
name = "Halo Alpha Fandom Wiki"
url = "halo.fandom.com"
mainpage = "Halo_Alpha"
content-path = "/wiki/"

[[en.origin]]
name = "Halo Wiki - Neoseeker"
url = "halo.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Halopedia"
url = "www.halopedia.org"
platform = "mediawiki"
icon = "halopedia.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/"
tags = [
    "recommended",
]

[fr]
name = "Halopedia"
icon = "wikihalo.png"

[[fr.origin]]
name = "Halopedia Fandom Wiki"
url = "halo.fandom.com/fr"
mainpage = "Halo_Nation"
content-path = "/wiki/"

[[fr.destination]]
name = "WikiHalo"
url = "wiki.halo.fr"
platform = "mediawiki"
icon = "wikihalo.png"
mainpage = "Accueil"
search-path = "/index.php"
content-path = "/"
tags = [
    "recommended",
]
