[en]
name = "Hanna-Barbera"
icon = "hannabarberawiki.png"

[[en.origin]]
name = "Hanna-Barbera Fandom Wiki"
url = "hanna-barbera.fandom.com"
mainpage = "Hanna-Barbera_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Hanna-Barbera Wiki"
url = "hanna-barberawiki.com"
platform = "mediawiki"
icon = "hannabarberawiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
