[en]
name = "Hearthstone"
icon = "hearthstonewiki.png"

[[en.origin]]
name = "Hearthstone Fandom Wiki"
url = "hearthstone.fandom.com"
mainpage = "Hearthstone_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Hearthstone Wiki - Neoseeker"
url = "hearthstone.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Hearthstone Wiki"
host = "wiki.gg"
url = "hearthstone.wiki.gg"
platform = "mediawiki"
icon = "hearthstonewiki.png"
mainpage = "Hearthstone_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
