[en]
origins_label = "HELLMET Fandom Wiki"
destination = "Hellmet Wiki"
destination_base_url = "hellmet.miraheze.org"
destination_platform = "mediawiki"
destination_icon = "hellmetwiki.png"
destination_main_page = "Main_Page"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"
destination_host = "Miraheze"

[[en.origins]]
origin = "HELLMET Fandom Wiki"
origin_base_url = "hellmet-roblox.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "HELLMET_Fandom"
