[en]
name = "HELLMET"
icon = "hellmetwiki.png"

[[en.origin]]
name = "HELLMET Fandom Wiki"
url = "hellmet-roblox.fandom.com"
mainpage = "HELLMET_Fandom"
content-path = "/wiki/"

[[en.destination]]
name = "Hellmet Wiki"
host = "Miraheze"
url = "hellmet.miraheze.org"
platform = "mediawiki"
icon = "hellmetwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
