[en]
origins_label = "Helldivers Fandom Wiki"
destination = "Helldivers Wiki"
destination_base_url = "helldivers.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "helldiverswiki.png"
destination_main_page = "Helldivers_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Helldivers Fandom Wiki"
origin_base_url = "helldivers.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Helldivers_Wiki"
