[en]
name = "Hello Neighbor"
icon = "helloneighborwiki.png"

[[en.origin]]
name = "Hello Neighbor Fandom Wiki"
url = "hello-neighbor.fandom.com"
mainpage = "Hello_Neighbor_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Hello Neighbor Wiki"
host = "wiki.gg"
url = "helloneighbor.wiki.gg"
platform = "mediawiki"
icon = "helloneighborwiki.png"
mainpage = "Hello_Neighbor_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
