[en]
origins_label = "Hollow Knight Fandom & Fextra Wikis"
destination = "Hollow Knight Wiki"
destination_base_url = "hollowknight.wiki"
destination_platform = "mediawiki"
destination_icon = "hollowknight.png"
destination_main_page = "Hollow_Knight_Wiki"
destination_search_path = "/mw/index.php"
destination_content_path = "/w/"

[[en.origins]]
origin = "Hollow Knight Fandom Wiki"
origin_base_url = "hollowknight.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Hollow_Knight_Wiki"

[[en.origins]]
origin = "Hollow Knight Fextralife Wiki"
origin_base_url = "hollowknight.wiki.fextralife.com"
origin_content_path = "/"
origin_main_page = "Hollow Knight Wiki"

[[en.origins]]
origin = "Hollow Knight Silksong Fextralife Wiki"
origin_base_url = "hollowknightsilksong.wiki.fextralife.com"
origin_content_path = "/"
origin_main_page = "Hollow Knight Silksong Wiki"
