[en]
name = "Hollow Knight"
icon = "hollowknight.png"

[[en.origin]]
name = "Hollow Knight Fandom Wiki"
url = "hollowknight.fandom.com"
mainpage = "Hollow_Knight_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Hollow Knight Fextralife Wiki"
url = "hollowknight.wiki.fextralife.com"
mainpage = "Hollow Knight Wiki"
content-path = "/"

[[en.origin]]
name = "Hollow Knight Silksong Fextralife Wiki"
url = "hollowknightsilksong.wiki.fextralife.com"
mainpage = "Hollow Knight Silksong Wiki"
content-path = "/"

[[en.destination]]
name = "Hollow Knight Wiki"
url = "hollowknight.wiki"
platform = "mediawiki"
icon = "hollowknight.png"
mainpage = "Hollow_Knight_Wiki"
search-path = "/mw/index.php"
content-path = "/w/"
tags = [
    "recommended",
]

[fr]
name = "Hollow Knight"
icon = "hollowknight.png"

[[fr.origin]]
name = "Hollow Knight Fandom Wiki"
url = "hollowknight.fandom.com/fr"
mainpage = "Accueil"
content-path = "/wiki/"

[[fr.destination]]
name = "Hollow Knight Wiki"
url = "fr.hollowknight.wiki"
platform = "mediawiki"
icon = "hollowknight.png"
mainpage = "Accueil"
search-path = "/mw/index.php"
content-path = "/w/"
tags = [
    "recommended",
]
