[en]
name = "HoloCure"
icon = "holocurewiki.png"

[[en.origin]]
name = "HoloCure Fandom Wiki"
url = "holocure.fandom.com"
mainpage = "HoloCure_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "HoloCure Wiki"
host = "wiki.gg"
url = "holocure.wiki.gg"
platform = "mediawiki"
icon = "holocurewiki.png"
mainpage = "HoloCure_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
