[en]
name = "HorizonXI"
icon = "horizonxiwiki.png"

[[en.origin]]
name = "HorizonXI Fandom Wiki"
url = "horizonxi.fandom.com"
mainpage = "HorizonXI_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "HorizonXI Wiki"
url = "horizonffxi.wiki"
platform = "mediawiki"
icon = "horizonxiwiki.png"
mainpage = "HorizonXI_Wiki"
search-path = "/w/index.php"
content-path = "/"
tags = [
    "recommended",
]
