[en]
name = "Horticular"
icon = "horticularwiki.png"

[[en.origin]]
name = "Horticular Fandom Wiki"
url = "horticular.fandom.com"
mainpage = "Horticular_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Horticular Wiki"
host = "wiki.gg"
url = "horticular.wiki.gg"
platform = "mediawiki"
icon = "horticularwiki.png"
mainpage = "Horticular_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
