[en]
name = "Hypnospace Outlaw"
icon = "hypnospacewiki.png"

[[en.origin]]
name = "Hypnospace Outlaw Fandom Wiki"
url = "hypnospace.fandom.com"
mainpage = "Hypnospace_Outlaw_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Hypnospace Wiki"
host = "wiki.gg"
url = "hypnospace.wiki.gg"
platform = "mediawiki"
icon = "hypnospacewiki.png"
mainpage = "Hypnospace_Outlaw_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
