[en]
origins_label = "IDOLiSH7 Fandom Wiki"
destination = "IDOLiSH7 Wiki"
destination_base_url = "idolish7.miraheze.org"
destination_platform = "mediawiki"
destination_icon = "idolish7.png"
destination_main_page = "Main_Page"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"
destination_host = "Miraheze"

[[en.origins]]
origin = "IDOLiSH7 Fandom Wiki"
origin_base_url = "idolish7.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "IDOLiSH7_Wiki"
