[en]
name = "Illusion Carnival"
icon = "illusioncarnivalwiki.png"

[[en.origin]]
name = "Illusion Carnival Fandom Wiki"
url = "illusion-carnival.fandom.com"
mainpage = "Illusion_Carnival_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Illusion Carnival Wiki"
host = "wiki.gg"
url = "illusioncarnival.wiki.gg"
platform = "mediawiki"
icon = "illusioncarnivalwiki.png"
mainpage = "Illusion_Carnival_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
