[en]
origins_label = "Illusion Carnival Fandom Wiki"
destination = "Illusion Carnival Wiki"
destination_base_url = "illusioncarnival.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "illusioncarnivalwiki.png"
destination_main_page = "Illusion_Carnival_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Illusion Carnival Fandom Wiki"
origin_base_url = "illusion-carnival.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Illusion_Carnival_Wiki"
