[en]
name = "Immortal Life"
icon = "immortallifewiki.png"

[[en.origin]]
name = "Immortal Life Fandom Wiki"
url = "immortal-life.fandom.com"
mainpage = "Immortal_Life_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Immortal Life Wiki"
host = "wiki.gg"
url = "immortallife.wiki.gg"
platform = "mediawiki"
icon = "immortallifewiki.png"
mainpage = "Immortal_Life_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
