[en]
name = "I Wanna Lockpick"
icon = "iwannalockpick.png"

[[en.origin]]
name = "I Wanna Lockpick Fandom Wiki"
url = "iwannalockpick.fandom.com"
mainpage = "I_Wanna_Lockpick_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "I Wanna Lockpick Wiki"
host = "Miraheze"
url = "iwannalockpickwiki.miraheze.org"
platform = "mediawiki"
icon = "iwannalockpick.png"
mainpage = "I_Wanna_Lockpick_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
