[en]
origins_label = "JoJo's Bizarre Wiki"
destination = "JoJo's Bizarre Encyclopedia"
destination_base_url = "jojowiki.com"
destination_platform = "mediawiki"
destination_icon = "jojo.png"
destination_main_page = "JoJo_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/"

[[en.origins]]
origin = "JoJo's Bizarre Wiki"
origin_base_url = "jojo.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Main_Page"
