[en]
origins_label = "Junk Jack Fandom Wiki"
destination = "Junk Jack Wiki"
destination_base_url = "junkjack.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "junkjackwiki.png"
destination_main_page = "Main_Page"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[en.origins]]
origin = "Junk Jack Fandom Wiki"
origin_base_url = "junkjack.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Junk_Jack_Wiki"
