[en]
name = "Kancolle"
icon = "kancollewiki.png"

[[en.origin]]
name = "Kancolle Fandom Wiki"
url = "kancolle.fandom.com"
mainpage = "KanColle_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Kancolle Wiki"
url = "en.kancollewiki.net"
platform = "mediawiki"
icon = "kancollewiki.png"
mainpage = "Kancolle_Wiki"
search-path = "/w/index.php"
content-path = "/"
