[en]
name = "Katawa Shoujo"
icon = "katawashoujo.png"

[[en.origin]]
name = "Katawa Shoujo Fandom Wiki"
url = "katawashoujo.fandom.com"
mainpage = "Katawa_Shoujo_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Katawa Shoujo Wiki"
url = "wiki.fhs.sh"
platform = "mediawiki"
icon = "katawashoujo.png"
mainpage = "Katawa_Shoujo_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
