[en]
name = "Japari Library"
icon = "japarilibrary.png"

[[en.origin]]
name = "Japari Library Fandom Wiki"
url = "kemono-friends.fandom.com"
mainpage = "Japari_Library_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Japari Library"
url = "japari-library.com"
platform = "mediawiki"
icon = "japarilibrary.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
