[en]
name = "Kerbal Space Program"
icon = "kerbalspaceprogramwiki.png"

[[en.origin]]
name = "Kerbal Space Program Fandom Wiki"
url = "kerbalspaceprogram.fandom.com"
mainpage = "Kerbal_Space_Program_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Kerbal Space Program Wiki"
url = "wiki.kerbalspaceprogram.com"
platform = "mediawiki"
icon = "kerbalspaceprogramwiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[fr]
name = "Kerbal Space Program"
icon = "kerbalspaceprogramwiki.png"

[[fr.origin]]
name = "Kerbal Space Program Fandom Wiki"
url = "kerbalspaceprogram.fandom.com/fr"
mainpage = "Wiki_KerbalSpaceProgram"
content-path = "/wiki/"

[[fr.destination]]
name = "Kerbal Space Program Wiki"
url = "wiki.kerbalspaceprogram.com"
platform = "mediawiki"
icon = "kerbalspaceprogramwiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
content-suffix = "/fr"
tags = [
    "official",
]
