[en]
name = "Kingdom Hearts Unchained X"
icon = "khuxwiki.png"

[[en.origin]]
name = "Kingdom Hearts Unchained X Fandom Wiki"
url = "unchainedx.fandom.com"
mainpage = "Kingdom_Hearts_Unchained_X_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "KHUX Wiki"
url = "www.khuxwiki.com"
platform = "mediawiki"
icon = "khuxwiki.png"
mainpage = "KHUX_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
