[en]
name = "The Kitatcho Laboratories"
icon = "kitatchowiki.png"

[[en.origin]]
name = "The Kitatcho Laboratories Fandom Wiki"
url = "kitatcho-labs.fandom.com"
mainpage = "The_Kitatcho_Laboratories_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "The Kitatcho Laboratories Wiki"
host = "wiki.gg"
url = "kitatcho.wiki.gg"
platform = "mediawiki"
icon = "kitatchowiki.png"
mainpage = "The_Kitatcho_Laboratories_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
