[en]
name = "Kuroshitsuji"
icon = "kuroshitsujiwiki.png"

[[en.origin]]
name = "Kuroshitsuji Fandom Wiki"
url = "kuroshitsuji.fandom.com"
mainpage = "Kuroshitsuji_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Kuroshitsuji Wiki"
host = "wiki.gg"
url = "kuroshitsuji.wiki.gg"
platform = "mediawiki"
icon = "kuroshitsujiwiki.png"
mainpage = "Kuroshitsuji_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
