[en]
origins_label = "Last Origin International Fandom Wiki"
destination = "Last Origin Wiki"
destination_base_url = "lastorigin.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "lastoriginwiki.png"
destination_main_page = "Last_Origin_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Last Origin International Fandom Wiki"
origin_base_url = "lastorigin.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Last_Origin_Wiki"
