[en]
name = "League of Legends"
icon = "leagueoflegendswiki.png"

[[en.origin]]
name = "League of Legends Fandom Wiki"
url = "leagueoflegends.fandom.com"
mainpage = "League_of_Legends_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "League of Legends Neoseeker Wiki"
url = "leagueoflegends.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "League of Legends Wiki"
url = "wiki.leagueoflegends.com"
platform = "mediawiki"
icon = "leagueoflegendswiki.png"
mainpage = "League_of_Legends_Wiki"
search-path = "/en-us/"
content-path = "/en-us/"
tags = [
    "official",
]
