[en]
name = "Leviathan Myth"
icon = "leviathanmythwikiofthedragons.png"

[[en.origin]]
name = "Leviathan Myth Fandom Wiki"
url = "leviathan-myth.fandom.com"
mainpage = "Leviathan_Myth_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Leviathan Myth Wiki"
host = "Miraheze"
url = "leviathanmyth.miraheze.org"
platform = "mediawiki"
icon = "leviathanmythwikiofthedragons.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
