[en]
name = "Lexington & Concord"
icon = "lexingtonconcordofficialwiki.png"

[[en.origin]]
name = "Lexington & Concord Fandom Wiki"
url = "lexington-and-concord.fandom.com"
mainpage = "Lexington_&_Concord_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Lexington & Concord Wiki"
host = "Miraheze"
url = "lexingtonandconcord.miraheze.org"
platform = "mediawiki"
icon = "lexingtonconcordofficialwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
