[en]
name = "Limbus Company"
icon = "limbuscompany.png"

[[en.origin]]
name = "Limbus Company Fandom Wiki"
url = "limbuscompany.fandom.com"
mainpage = "Limbus_Company_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Limbus Company Wiki"
host = "wiki.gg"
url = "limbuscompany.wiki.gg"
platform = "mediawiki"
icon = "limbuscompany.png"
mainpage = "Limbus_Company_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
