[en]
name = "Linkin Park"
icon = "linkinpedia.png"

[[en.origin]]
name = "Linkin Park Fandom Wiki"
url = "linkinpark.fandom.com"
mainpage = "Linkin_Park_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Linkinpedia"
url = "linkinpedia.com"
platform = "mediawiki"
icon = "linkinpedia.png"
mainpage = "Main_Page"
search-path = "/www/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
