[en]
name = "Little King's Story"
icon = "littlekingsstorywiki.png"

[[en.origin]]
name = "Little King's Story Fandom Wiki"
url = "littlekingsstory.fandom.com"
mainpage = "Little_King's_Story_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Little King's Story Wiki"
host = "wiki.gg"
url = "littlekingsstory.wiki.gg"
platform = "mediawiki"
icon = "littlekingsstorywiki.png"
mainpage = "Little_King's_Story_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
