[en]
name = "Shadows Over Loathing"
icon = "wikiofloathing.png"

[[en.origin]]
name = "Shadows Over Loathing Fandom Wiki"
url = "shadowsoverloathing.fandom.com"
mainpage = "Shadows_Over_Loathing_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Wiki of Loathing"
host = "wiki.gg"
url = "loathing.wiki.gg"
platform = "mediawiki"
icon = "wikiofloathing.png"
mainpage = "Wiki_of_Loathing"
search-path = "/index.php"
content-path = "/wiki/"
