[en]
name = "Lorcana"
icon = "mushureport.png"

[[en.origin]]
name = "Lorcana Fandom Wiki"
url = "lorcana.fandom.com"
mainpage = "Lorcana_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Mushu Report's Lorcana Wiki"
url = "wiki.mushureport.com"
platform = "mediawiki"
icon = "mushureport.png"
mainpage = "Mushu_Report"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
