[en]
origins_label = "LOVE-BULLET Fandom Wiki"
destination = "LOVE-BULLET Wiki"
destination_base_url = "lovebullet.wiki"
destination_platform = "mediawiki"
destination_icon = "lovebullet.png"
destination_main_page = "Main_Page"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"
destination_host = "Miraheze"

[[en.origins]]
origin = "LOVE-BULLET Fandom Wiki"
origin_base_url = "love-bullet.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "LOVE-BULLET_Wiki"
