[en]
name = "LOVE-BULLET"
icon = "lovebullet.png"

[[en.origin]]
name = "LOVE-BULLET Fandom Wiki"
url = "love-bullet.fandom.com"
mainpage = "LOVE-BULLET_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "LOVE-BULLET Wiki"
host = "Miraheze"
url = "lovebullet.wiki"
platform = "mediawiki"
icon = "lovebullet.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
