[en]
name = "Mabinogi"
icon = "mabinogiworldwiki.png"

[[en.origin]]
name = "Mabinogi Fandom Wiki"
url = "mabinogi.fandom.com"
mainpage = "Mabinogi_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Mabinogi World Wiki"
url = "wiki.mabinogiworld.com"
platform = "mediawiki"
icon = "mabinogiworldwiki.png"
mainpage = "Wiki_Home"
search-path = "/index.php"
content-path = "/view/"
tags = [
    "recommended",
]
