[en]
origins_label = "Madoka Magica Fandom Wiki"
destination = "Puella Magi Wiki"
destination_base_url = "wiki.puella-magi.net"
destination_platform = "mediawiki"
destination_icon = "puellamagi.png"
destination_main_page = "Main_Page"
destination_search_path = "/w/index.php"
destination_content_path = "/"

[[en.origins]]
origin = "Madoka Magica Fandom Wiki"
origin_base_url = "madoka.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Madoka_Magica_Wiki"
