[en]
name = "Madoka Magica"
icon = "puellamagi.png"

[[en.origin]]
name = "Madoka Magica Fandom Wiki"
url = "madoka.fandom.com"
mainpage = "Madoka_Magica_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Puella Magi Wiki"
url = "wiki.puella-magi.net"
platform = "mediawiki"
icon = "puellamagi.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/"
tags = [
    "recommended",
]
