[en]
name = "Wiki of Mana"
icon = "wikiofmana.png"

[[en.origin]]
name = "Wiki of Mana Fandom Wiki"
url = "mana.fandom.com"
mainpage = "Wiki_of_Mana"
content-path = "/wiki/"

[[en.destination]]
name = "Wiki of Mana"
url = "wikiofmana.com"
platform = "mediawiki"
icon = "wikiofmana.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
