[en]
origins_label = "Wiki of Mana Fandom Wiki"
destination = "Wiki of Mana"
destination_base_url = "wikiofmana.com"
destination_platform = "mediawiki"
destination_icon = "wikiofmana.png"
destination_main_page = "Main_Page"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"

[[en.origins]]
origin = "Wiki of Mana Fandom Wiki"
origin_base_url = "mana.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Wiki_of_Mana"
