[en]
name = "Manor Lords"
icon = "manorlordswiki.png"

[[en.origin]]
name = "Manor Lords Fandom Wiki"
url = "manor-lords.fandom.com"
mainpage = "Manor_Lords_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Manor Lords Wiki"
host = "Hooded Horse"
url = "hoodedhorse.com/wiki/Manor_Lords"
platform = "mediawiki"
icon = "manorlordswiki.png"
mainpage = "Manor_Lords_Official_Wiki"
search-path = "/index.php"
content-path = "/"
tags = [
    "official",
]
