[en]
name = "Megabonk"
icon = "megabonkwiki.png"

[[en.origin]]
name = "Megabonk Fandom Wiki"
url = "megabonk.fandom.com"
mainpage = "Megabonk_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Megabonk Wiki"
url = "megabonk.wiki"
platform = "mediawiki"
icon = "megabonkwiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
