[fr]
name = "Metin2"
icon = "metin2wiki.png"

[[fr.origin]]
name = "Metin2 Fandom Wiki"
url = "metin2.fandom.com/fr"
mainpage = "Accueil"
content-path = "/wiki/"

[[fr.destination]]
name = "Metin2 Wiki"
url = "fr-wiki.metin2.gameforge.com"
platform = "mediawiki"
icon = "metin2wiki.png"
mainpage = "Accueil"
search-path = "/index.php"
content-path = "/index.php/"
tags = [
    "official",
    "recommended",
]
