[en]
name = "Mewgenics"
icon = "mewgenicswiki.png"

[[en.origin]]
name = "Mewgenics Fandom Wiki"
url = "mewgenics.fandom.com"
mainpage = "Mewgenics_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Mewgenics Wiki"
host = "wiki.gg"
url = "mewgenics.wiki.gg"
platform = "mediawiki"
icon = "mewgenicswiki.png"
mainpage = "Mewgenics_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
