[en]
name = "Mii"
icon = "miiwiki.png"

[[en.origin]]
name = "Mii Fandom Wiki"
url = "miiwiki.fandom.com"
mainpage = "Mii_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "MiiWiki"
url = "miiwiki.org"
platform = "mediawiki"
icon = "miiwiki.png"
mainpage = "Mii_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
