[en]
name = "Milk Series"
icon = "milkserieswiki.png"

[[en.origin]]
name = "Milk Series Fandom Wiki"
url = "milk-games.fandom.com"
mainpage = "Milk_Series_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Milk Series Wiki"
host = "wiki.gg"
url = "milk.wiki.gg"
platform = "mediawiki"
icon = "milkserieswiki.png"
mainpage = "Milk_Series_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
