[en]
origins_label = "Minehut Fandom Wikis"
destination = "Minehut Wiki"
destination_base_url = "minehut.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "minehutwiki.png"
destination_main_page = "Minehut_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Minehut Fandom Wiki"
origin_base_url = "minehut.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Minehut_Wiki"

[[en.origins]]
origin = "Minehut MC Fandom Wiki"
origin_base_url = "minehutmc.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Minehut_Wiki"
