[en]
name = "Marvel Superheroes Mod"
icon = "marvelsuperheroesmodwiki.png"

[[en.origin]]
name = "Marvel Superheroes Mod Fandom Wiki"
url = "marvel-superheroes-mod.fandom.com"
mainpage = "Marvel_Superheroes_Mod_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Marvel Superheroes Mod Wiki"
host = "wiki.gg"
url = "marvelsuperheroesmod.wiki.gg"
platform = "mediawiki"
icon = "marvelsuperheroesmodwiki.png"
mainpage = "Marvel_Superheroes_Mod_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
