[en]
name = "Minicraft"
icon = "minicraftwiki.png"

[[en.origin]]
name = "Minicraft Fandom Wiki"
url = "minicraft.fandom.com"
mainpage = "Minicraft_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Minicraft Wiki"
host = "wiki.gg"
url = "minicraft.wiki.gg"
platform = "mediawiki"
icon = "minicraftwiki.png"
mainpage = "Minicraft_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
