[en]
name = "MiSide"
icon = "misidewiki.png"

[[en.origin]]
name = "MiSide Fandom Wiki"
url = "miside.fandom.com"
mainpage = "MiSide_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "MiSide Wiki"
host = "wiki.gg"
url = "miside.wiki.gg"
platform = "mediawiki"
icon = "misidewiki.png"
mainpage = "MiSide_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
