[en]
origins_label = "Monster Prom Fandom Wiki"
destination = "Monster Prom Wiki"
destination_base_url = "monsterprom.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "monsterpromwiki.png"
destination_content_path = "/wiki/"
destination_search_path = "/index.php"
destination_main_page = "Monster_Prom_Wiki"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Monster Prom Fandom Wiki"
origin_base_url = "monster-prom.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Monster_Prom_Wiki"
