[en]
name = "Moshi Monsters"
icon = "moshimonsterswiki.png"

[[en.origin]]
name = "Moshi Monsters Fandom Wiki"
url = "moshimonsters.fandom.com"
mainpage = "Moshi_Monsters_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Moshi Monsters Wiki"
host = "wiki.gg"
url = "moshimonsters.wiki.gg"
platform = "mediawiki"
icon = "moshimonsterswiki.png"
mainpage = "Moshi_Monsters_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
