[en]
name = "Mystery Dungeon"
icon = "mysterydungeon.png"

[[en.origin]]
name = "Mystery Dungeon Fandom Wiki"
url = "mysterydungeon.fandom.com"
mainpage = "Mystery_Dungeon_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Pokémon Mystery Dungeon Fandom Wiki"
url = "pmd-rt-archive.fandom.com"
mainpage = "Pokémon_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Mystery Dungeon Wiki"
url = "mysterydungeonwiki.com"
platform = "mediawiki"
icon = "mysterydungeon.png"
mainpage = "Mystery_Dungeon_Franchise_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
