[en]
name = "Nebulamancers"
icon = "nebulamancerswiki.png"

[[en.origin]]
name = "Nebulamancers Fandom Wiki"
url = "nebulamancers.fandom.com"
mainpage = "Nebulamancers_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Nebulamancers Wiki"
host = "Miraheze"
url = "nebulamancers.miraheze.org"
platform = "mediawiki"
icon = "nebulamancerswiki.png"
mainpage = "Nebulamancers_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
