[en]
name = "NecroMerger"
icon = "necromergerwiki.png"

[[en.origin]]
name = "NecroMerger Fandom Wiki"
url = "necromerger.fandom.com"
mainpage = "NecroMerger"
content-path = "/wiki/"

[[en.destination]]
name = "NecroMerger Wiki"
host = "wiki.gg"
url = "necromerger.wiki.gg"
platform = "mediawiki"
icon = "necromergerwiki.png"
mainpage = "NecroMerger_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
