[en]
name = "Neocron Guide"
icon = "neocronwiki.png"

[[en.origin]]
name = "Neocron Guide Fandom Wiki"
url = "neocron-guide.fandom.com"
mainpage = "Neocron_Guide_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Neocron Wiki"
url = "wiki.techhaven.org"
platform = "mediawiki"
icon = "neocronwiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/"
tags = [
    "recommended",
]
