[en]
name = "NetHack"
icon = "nethack.png"

[[en.origin]]
name = "NetHack Fandom Wiki"
url = "nethack.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "NetHackWiki"
url = "nethackwiki.com"
platform = "mediawiki"
icon = "nethack.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
