[en]
origins_label = "Nichijou Fandom Wiki"
destination = "Nichijou Wiki"
destination_base_url = "nichijou.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "nichijou.png"
destination_content_path = "/wiki/"
destination_search_path = "/index.php"
destination_main_page = "Nichijou_Wiki"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Nichijou Fandom Wiki"
origin_base_url = "nichijou.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Nichijou_Wiki"
