[en]
name = "Nichijou"
icon = "nichijou.png"

[[en.origin]]
name = "Nichijou Fandom Wiki"
url = "nichijou.fandom.com"
mainpage = "Nichijou_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Nichijou Wiki"
host = "wiki.gg"
url = "nichijou.wiki.gg"
platform = "mediawiki"
icon = "nichijou.png"
mainpage = "Nichijou_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
