[en]
name = "Nico's Nextbots"
icon = "nicosnextbotswiki.png"

[[en.origin]]
name = "Nico's Nextbots Fandom Wiki"
url = "nicos-nextbots.fandom.com"
mainpage = "Nico's_Nextbots_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Nico's Nextbots Wiki"
host = "Miraheze"
url = "nicosnextbots.miraheze.org"
platform = "mediawiki"
icon = "nicosnextbotswiki.png"
mainpage = "Nico's_Nextbots_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
