[en]
name = "Nightmare Reaper"
icon = "nightmarereaperwiki.png"

[[en.origin]]
name = "Nightmare Reaper Fandom Wiki"
url = "nightmare-reaper.fandom.com"
mainpage = "Nightmare_Reaper_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Nightmare Reaper Wiki"
host = "wiki.gg"
url = "nightmarereaper.wiki.gg"
platform = "mediawiki"
icon = "nightmarereaperwiki.png"
mainpage = "Nightmare_Reaper_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
