[en]
name = "Nine Inch Nails"
icon = "nineinchnails.png"

[[en.origin]]
name = "Nine Inch Nails Fandom Wiki"
url = "nin.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "NinWiki"
url = "www.nin.wiki"
platform = "mediawiki"
icon = "nineinchnails.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/"
