[en]
name = "HBM's Nuclear Tech"
icon = "nucleartechwiki.png"

[[en.origin]]
name = "HBM's Nuclear Tech Fandom Wiki"
url = "ntm.fandom.com"
mainpage = "HBM's_Nuclear_Tech_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "HBM's Nuclear Tech Wiki"
url = "nucleartech.wiki"
platform = "mediawiki"
icon = "nucleartechwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
