[en]
origins_label = "OathBreakersVr Fandom Wiki"
destination = "Oathbreakers VR Wiki"
destination_base_url = "oathbreakersvr.miraheze.org"
destination_platform = "mediawiki"
destination_icon = "oathbreakersvr.png"
destination_main_page = "Main_Page"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"
destination_host = "Miraheze"

[[en.origins]]
origin = "OathBreakersVr Fandom Wiki"
origin_base_url = "oathbreakersvr.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "OathBreakersVr_Wiki"
