[en]
name = "OathBreakersVr"
icon = "oathbreakersvr.png"

[[en.origin]]
name = "OathBreakersVr Fandom Wiki"
url = "oathbreakersvr.fandom.com"
mainpage = "OathBreakersVr_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Oathbreakers VR Wiki"
host = "Miraheze"
url = "oathbreakersvr.miraheze.org"
platform = "mediawiki"
icon = "oathbreakersvr.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
