[en]
origins_label = "Obey Me! Fandom Wiki"
destination = "Obey Me Wiki"
destination_base_url = "obeymewiki.com"
destination_platform = "mediawiki"
destination_icon = "obeymewiki.png"
destination_main_page = "Main"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"

[[en.origins]]
origin = "Obey Me! Fandom Wiki"
origin_base_url = "obey-me.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Obey_Me!_Wiki"
