[en]
name = "Obey Me!"
icon = "obeymewiki.png"

[[en.origin]]
name = "Obey Me! Fandom Wiki"
url = "obey-me.fandom.com"
mainpage = "Obey_Me!_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Obey Me Wiki"
url = "obeymewiki.com"
platform = "mediawiki"
icon = "obeymewiki.png"
mainpage = "Main"
search-path = "/index.php"
content-path = "/wiki/"
