[en]
name = "Old School Runescape"
icon = "oldschoolrunescape.png"

[[en.origin]]
name = "Old School Runescape Fandom Wiki"
url = "oldschoolrunescape.fandom.com"
mainpage = "Old_School_RuneScape_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "OSRS Wiki"
url = "oldschool.runescape.wiki"
platform = "mediawiki"
icon = "oldschoolrunescape.png"
mainpage = "Old_School_RuneScape_Wiki"
search-path = "/"
content-path = "/w/"
tags = [
    "official",
]
