[en]
name = "Omega Strikers"
icon = "omegastrikerswiki.png"

[[en.origin]]
name = "Omega Strikers Fandom Wiki"
url = "omegastrikers.fandom.com"
mainpage = "Omega_Strikers_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Omega Strikers Wiki"
host = "wiki.gg"
url = "omegastrikers.wiki.gg"
platform = "mediawiki"
icon = "omegastrikerswiki.png"
mainpage = "Omega_Strikers_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
