[en]
name = "OpenStreetMap"
icon = "openstreetmapwiki.png"

[[en.origin]]
name = "OpenStreetMap Fandom Wiki"
url = "openstreetmap-online.fandom.com"
mainpage = "OpenStreetMap_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "OpenStreetMap Wiki"
url = "wiki.openstreetmap.org"
platform = "mediawiki"
icon = "openstreetmapwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
