[en]
name = "Otherkin"
icon = "otherkinwiki.png"

[[en.origin]]
name = "Otherkin Fandom Wiki"
url = "otherkin.fandom.com"
mainpage = "Otherkin_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Otherkin Wiki"
host = "miraheze"
url = "otherkin.wiki"
platform = "mediawiki"
icon = "otherkinwiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
