[en]
name = "Pacific Drive"
icon = "pacificdrivewiki.png"

[[en.origin]]
name = "Pacific Drive Fandom Wiki"
url = "pacific-drive.fandom.com"
mainpage = "Pacific_Drive_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Pacific Drive Wiki"
url = "pacificdrive.wiki"
platform = "mediawiki"
icon = "pacificdrivewiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/view/"
tags = [
    "recommended",
]
