[en]
name = "The Pale Beyond"
icon = "thepalebeyondwiki.png"

[[en.origin]]
name = "The Pale Beyond Fandom Wiki"
url = "pale-beyond.fandom.com"
mainpage = "The_Pale_Beyond_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "The Pale Beyond Wiki"
host = "wiki.gg"
url = "thepalebeyond.wiki.gg"
platform = "mediawiki"
icon = "thepalebeyondwiki.png"
mainpage = "The_Pale_Beyond_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
