[en]
name = "Palworld"
icon = "palworldwiki.png"

[[en.origin]]
name = "Palworld Fandom Wiki"
url = "palworld.fandom.com"
mainpage = "Palworld_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Palworld Wiki"
host = "wiki.gg"
url = "palworld.wiki.gg"
platform = "mediawiki"
icon = "palworldwiki.png"
mainpage = "Palworld_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
