[en]
name = "Pathologic"
icon = "pathologicwiki.png"

[[en.origin]]
name = "Pathologic Fandom Wiki"
url = "pathologic.fandom.com"
mainpage = "Pathologic_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Pathologic Wiki"
host = "wiki.gg"
url = "pathologic.wiki.gg"
platform = "mediawiki"
icon = "pathologicwiki.png"
mainpage = "Pathologic_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
