[en]
name = "Path to Nowhere"
icon = "pathtonowherewiki.png"

[[en.origin]]
name = "Path to Nowhere Fandom Wiki"
url = "path-to-nowhere.fandom.com"
mainpage = "Path_To_Nowhere_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Path to Nowhere Wiki"
host = "wiki.gg"
url = "pathtonowhere.wiki.gg"
platform = "mediawiki"
icon = "pathtonowherewiki.png"
mainpage = "Path_To_Nowhere_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
