[en]
name = "Path of Exile"
icon = "pathofexile.png"

[[en.origin]]
name = "Path of Exile Fandom Wiki"
url = "pathofexile.fandom.com"
mainpage = "Path_of_Exile_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Path of Exile Wiki"
url = "www.poewiki.net"
platform = "mediawiki"
icon = "pathofexile.png"
mainpage = "Path_of_Exile_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
