[en]
name = "Path of Exile 2 Wikis"
icon = "pathofexile2.png"

[[en.origin]]
name = "Path of Exile 2 Fextralife Wiki"
url = "pathofexile2.wiki.fextralife.com"
mainpage = "Path of Exile 2 Wiki"
content-path = "/"

[[en.origin]]
name = "Path of Exile 2 Fandom Wiki"
url = "path-of-exile-2.fandom.com"
mainpage = "Path_of_Exile_2_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Path of Exile 2 Wiki"
url = "www.poe2wiki.net"
platform = "mediawiki"
icon = "pathofexile2.png"
mainpage = "Path_of_Exile_2_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
