[en]
name = "PCSX2"
icon = "pcsx2.png"

[[en.origin]]
name = "PCSX2 Fandom Wiki"
url = "pcsx2-emu.fandom.com"
mainpage = "PCSX2_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "PCSX2 Wiki"
url = "wiki.pcsx2.net"
platform = "mediawiki"
icon = "pcsx2.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/"
tags = [
    "recommended",
]
