[en]
name = "Peak"
icon = "peakwiki.png"

[[en.origin]]
name = "Peak Fandom Wiki"
url = "peakgame.fandom.com"
mainpage = "Peak_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "PEAK Wiki"
host = "wiki.gg"
url = "peak.wiki.gg"
platform = "wiki.gg"
icon = "peakwiki.png"
mainpage = "PEAK_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
