[en]
origins_label = "PHIGHTING! Fandom Wiki"
destination = "PHIGHTING! Wiki"
destination_base_url = "phighting.wiki"
destination_platform = "mediawiki"
destination_icon = "phightingwiki.png"
destination_main_page = "PHIGHTING!_Wiki"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"
destination_host = "Miraheze"
tags = [
    "official",
]

[[en.origins]]
origin = "PHIGHTING! Fandom Wiki"
origin_base_url = "phighting.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "PHIGHTING!_Wiki"
