[en]
name = "Pikmin Fanon"
icon = "pikminfanon.png"

[[en.origin]]
name = "Pikmin Fanon Fandom Wiki"
url = "pikminfanon.fandom.com"
mainpage = "Pikmin_Fanon_Wikia"
content-path = "/wiki/"

[[en.destination]]
name = "Pikmin Fanon"
url = "pikminfanon.com"
platform = "mediawiki"
icon = "pikminfanon.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
