[en]
name = "Pixar Cars"
icon = "disneypixarcarswiki.png"

[[en.origin]]
name = "Pixar Cars Fandom Wiki"
url = "pixarcars.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Disney•Pixar CARS Wiki"
url = "dpcarswiki.com"
platform = "mediawiki"
icon = "disneypixarcarswiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/"
