[en]
name = "Pizza Tower"
icon = "pizzatowerwiki.png"

[[en.origin]]
name = "Pizza Tower Fandom Wiki"
url = "pizzatower.fandom.com"
mainpage = "Pizza_Tower_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Pizza Tower Wiki"
host = "Miraheze"
url = "pizzatower.wiki"
platform = "mediawiki"
icon = "pizzatowerwiki.png"
mainpage = "Pizza_Tower_Wiki:Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
