[en]
origins_label = "Plague Inc. Fandom Wiki"
destination = "Plague Inc. Wiki"
destination_base_url = "plagueinc.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "plagueincwiki.png"
destination_main_page = "Plague_Inc._Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Plague Inc. Fandom Wiki"
origin_base_url = "plagueinc.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Plague_Inc._Wiki"
