[en]
name = "Plague Inc."
icon = "plagueincwiki.png"

[[en.origin]]
name = "Plague Inc. Fandom Wiki"
url = "plagueinc.fandom.com"
mainpage = "Plague_Inc._Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Plague Inc. Wiki"
host = "wiki.gg"
url = "plagueinc.wiki.gg"
platform = "mediawiki"
icon = "plagueincwiki.png"
mainpage = "Plague_Inc._Wiki"
search-path = "/index.php"
content-path = "/wiki/"
