[en]
name = "Pleasant Goat"
icon = "xyywiki.png"

[[en.origin]]
name = "Pleasant Goat Fandom Wiki"
url = "xyy.fandom.com"
mainpage = "Pleasant_Goat_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Pleasant Goat Wiki"
host = "Miraheze"
url = "xyy.miraheze.org"
platform = "mediawiki"
icon = "xyywiki.png"
mainpage = "Pleasant_Goat_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
