[en]
name = "Plural"
icon = "plural.png"

[[en.origin]]
name = "Plural Fandom Wiki"
url = "plural.fandom.com"
mainpage = "Plural_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Pluralpedia"
url = "pluralpedia.org"
platform = "mediawiki"
icon = "plural.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/w/"
