[en]
name = "Pokemon Infinity"
icon = "pokemoninfinity.png"

[[en.origin]]
name = "Pokemon Infinity Fandom Wiki"
url = "p-infinity.fandom.com"
mainpage = "Pokemon_Infinity_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Pokémon Infinity Wiki"
host = "Miraheze"
url = "pokemoninfinity.miraheze.org"
platform = "mediawiki"
icon = "pokemoninfinity.png"
mainpage = "Pokemon_Infinity_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
