[en]
name = "Pokemon Unbound"
icon = "pokemonunboundwiki.png"

[[en.origin]]
name = "Pokemon Unbound Fandom Wiki"
url = "pokemonunbound.fandom.com"
mainpage = "Pokemon_Unbound_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Pokémon Unbound Wiki"
host = "Miraheze"
url = "pokemonunbound.miraheze.org"
platform = "mediawiki"
icon = "pokemonunboundwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
