[en]
name = "Popira"
icon = "popirawiki.png"

[[en.origin]]
name = "Popira Fandom Wiki"
url = "popira.fandom.com"
mainpage = "Popira_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Popira Wiki"
url = "popira20.com/wiki"
platform = "mediawiki"
icon = "popirawiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/index.php?title="
