[ru]
name = "Pou"
icon = "poupedia.png"

[[ru.origin]]
name = "Pou Fandom Wiki"
url = "pou.fandom.com/ru"
mainpage = "Pou_вики"
content-path = "/wiki/"

[[ru.destination]]
name = "Poupedia"
host = "Miraheze"
url = "poupedia.com"
platform = "mediawiki"
icon = "poupedia.png"
mainpage = "Poupedia"
search-path = "/w/index.php"
content-path = "/"

[en]
name = "Pou"
icon = "poupedia.png"

[[en.origin]]
name = "Pou Fandom Wiki"
url = "pou.fandom.com"
mainpage = "Pou_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Poupedia"
host = "Miraheze"
url = "poupedia.com"
platform = "mediawiki"
icon = "poupedia.png"
mainpage = "Poupedia"
search-path = "/w/index.php"
content-path = "/"

[hr]
name = "Pou"
icon = "poupedija.png"

[[hr.origin]]
name = "Pou Fandom Wiki"
url = "pou.fandom.com/hr"
mainpage = "Pou_Wiki"
content-path = "/wiki/"

[[hr.destination]]
name = "Poupedija"
host = "Miraheze"
url = "poupedia.com"
platform = "mediawiki"
icon = "poupedija.png"
mainpage = "Poupedia"
search-path = "/w/index.php"
content-path = "/"
