[en]
name = "Project Wingman"
icon = "projectwingmanwiki.png"

[[en.origin]]
name = "Project Wingman Fandom Wiki"
url = "projectwingman.fandom.com"
mainpage = "Project_Wingman_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Project Wingman Wiki"
host = "wiki.gg"
url = "projectwingman.wiki.gg"
platform = "mediawiki"
icon = "projectwingmanwiki.png"
mainpage = "Project_Wingman_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
