[en]
name = "Project SEKAI"
icon = "sekaipedia.png"

[[en.origin]]
name = "Project SEKAI Fandom Wiki"
url = "projectsekai.fandom.com"
mainpage = "Project_SEKAI_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Sekaipedia"
host = "Miraheze"
url = "www.sekaipedia.org"
platform = "mediawiki"
icon = "sekaipedia.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
