[en]
name = "Project Zomboid"
icon = "pzwiki.png"

[[en.origin]]
name = "Project Zomboid Fandom Wiki"
url = "projectzomboid.fandom.com"
mainpage = "Project_Zomboid_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Project Zomboid Wiki"
url = "pzwiki.net"
platform = "mediawiki"
icon = "pzwiki.png"
mainpage = "Project_Zomboid_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
