[en]
name = "Project Gorgon"
icon = "projectgorgon.png"

[[en.origin]]
name = "Project Gorgon Fandom Wiki"
url = "project-gorgon.fandom.com"
mainpage = "Project_Gorgon_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Project: Gorgon Wiki"
url = "wiki.projectgorgon.com"
platform = "mediawiki"
icon = "projectgorgon.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
