[en]
name = "Protochroma"
icon = "protochromawiki.png"

[[en.origin]]
name = "Protochroma Fandom Wiki"
url = "protochroma.fandom.com"
mainpage = "Protochroma_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Protochroma Wiki"
url = "protochroma.wiki"
platform = "mediawiki"
icon = "protochromawiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/view/"
