[en]
name = "PUBG"
icon = "pubgwiki.png"

[[en.origin]]
name = "PUBG Fandom Wiki"
url = "pubg.fandom.com"
mainpage = "PLAYERUNKNOWNS_BATTLEGROUNDS_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "PUBG Wiki"
host = "wiki.gg"
url = "pubg.wiki.gg"
platform = "mediawiki"
icon = "pubgwiki.png"
mainpage = "PUBG_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
