[en]
name = "Python"
icon = "pythonwiki.png"

[[en.origin]]
name = "Python Fandom Wiki"
url = "python.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Python Wiki"
url = "wiki.python.org"
platform = "moinmoin"
icon = "pythonwiki.png"
mainpage = "FrontPage"
search-path = "/moin/"
content-path = "/moin/"
tags = [
    "official",
]
