[en]
name = "Rabbit and Steel"
icon = "rabbitandsteelwiki.png"

[[en.origin]]
name = "Rabbit and Steel Fandom Wiki"
url = "rabbitandsteel.fandom.com"
mainpage = "Rabbit_and_Steel_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Rabbit and Steel Wiki"
host = "Miraheze"
url = "rns.miraheze.org"
platform = "mediawiki"
icon = "rabbitandsteelwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
