[ru]
name = "Rain World"
icon = "rainworld.png"

[[ru.origin]]
name = "Rain World Fandom Wiki"
url = "rainworld.fandom.com/ru"
mainpage = "Rain_World_Wiki_Rus"
content-path = "/wiki/"

[[ru.destination]]
name = "Rain World Wiki"
host = "Miraheze"
url = "rainworld.miraheze.org"
platform = "mediawiki"
icon = "rainworld.png"
mainpage = "Rain_World_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
content-suffix = "/ru"
tags = [
    "official",
    "recommended",
]

[en]
name = "Rain World"
icon = "rainworld.png"

[[en.origin]]
name = "Rain World Fandom Wiki"
url = "rain-world-game.fandom.com"
mainpage = "Rain_World_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Rain World 007 Fandom Wiki"
url = "rain-world07.fandom.com"
mainpage = "Rain_world_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Rain World Wiki"
host = "Miraheze"
url = "rainworld.miraheze.org"
platform = "mediawiki"
icon = "rainworld.png"
mainpage = "Rain_World_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
