[en]
name = "Rain (web comic)"
icon = "rainversewiki.png"

[[en.origin]]
name = "Rain (web comic) Fandom Wiki"
url = "rain-web-comic.fandom.com"
mainpage = "Rain_(web_comic)_Wikia"
content-path = "/wiki/"

[[en.origin]]
name = "Rain (webcomic) Fandom Wiki"
url = "rain-webcomic.fandom.com"
mainpage = "Rain_(webcomic)_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "My Impossible Soulmate Fandom Wiki"
url = "myimpossiblesoulmate.fandom.com"
mainpage = "My_Impossible_Soulmate_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Rainverse Wiki"
host = "Miraheze"
url = "rainverse.wiki"
platform = "mediawiki"
icon = "rainversewiki.png"
mainpage = "Rainverse_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
