[en]
origins_label = "Rammstein Fandom Wiki"
destination = "RammWiki"
destination_base_url = "rammwiki.net"
destination_platform = "mediawiki"
destination_icon = "ramm.png"
destination_main_page = "Main_Page"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"

[[en.origins]]
origin = "Rammstein Fandom Wiki"
origin_base_url = "rammstein.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Rammstein_Wiki"
