[en]
name = "Ratatan"
icon = "ratatan.png"

[[en.origin]]
name = "Ratatan Fandom Wiki"
url = "ratatan.fandom.com"
mainpage = "Ratatan_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Ratatan Wiki"
host = "wiki.gg"
url = "ratatan.wiki.gg"
platform = "mediawiki"
icon = "ratatan.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
