[en]
origins_label = "RollerCoaster Tycoon Fandom Wiki"
destination = "RollerCoaster Tycoon Wiki"
destination_base_url = "rct.wiki"
destination_platform = "mediawiki"
destination_icon = "rctwiki.png"
destination_main_page = "RollerCoaster_Tycoon_Wiki"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"
destination_host = "Miraheze"

[[en.origins]]
origin = "RollerCoaster Tycoon Fandom Wiki"
origin_base_url = "rct.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "RollerCoaster_Tycoon_Wiki"
