[en]
name = "Red Flood Mod"
icon = "redfloodwiki.png"

[[en.origin]]
name = "Red Flood Mod Fandom Wiki"
url = "red-flood.fandom.com"
mainpage = "Red_Flood_Mod_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Red Flood Mod Wiki"
host = "wiki.gg"
url = "redflood.wiki.gg"
platform = "mediawiki"
icon = "redfloodwiki.png"
mainpage = "Red_Flood_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
