[en]
name = "Rhythm Doctor"
icon = "rhythmdoctorwiki.png"

[[en.origin]]
name = "Rhythm Doctor Fandom Wiki"
url = "rhythm-doctor.fandom.com"
mainpage = "Rhythm_Doctor_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Rhythm Doctor Wiki"
url = "wiki.rhythm.cafe"
platform = "mediawiki"
icon = "rhythmdoctorwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/page/"
tags = [
    "recommended",
]
