[en]
name = "Ricochet"
icon = "ricochet.png"

[[en.origin]]
name = "Ricochet Universe Fandom Wiki"
url = "ricochet-universe.fandom.com"
mainpage = "Ricochet_Universe_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Ricochet Lost Worlds Fandom Wiki"
url = "ricochetlw.fandom.com"
mainpage = "Ricochet_Lost_Worlds_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Ricochet Wiki"
host = "Miraheze"
url = "wiki.ricochetuniverse.com"
platform = "mediawiki"
icon = "ricochet.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
