[en]
name = "Mahjong"
icon = "japanesemahjongwiki.png"

[[en.origin]]
name = "Mahjong Fandom Wiki"
url = "mahjong.fandom.com"
mainpage = "Mahjong_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Japanese Mahjong Wiki"
url = "riichi.wiki"
platform = "mediawiki"
icon = "japanesemahjongwiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/"
tags = [
    "recommended",
]
