[en]
name = "RLCraft"
icon = "rlcraft.png"

[[en.origin]]
name = "RLCraft Fandom Wiki"
url = "rlcraft.fandom.com"
mainpage = "RLCraft_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "RLCraft Wiki"
host = "wiki.gg"
url = "rlcraft.wiki.gg"
platform = "mediawiki"
icon = "rlcraft.png"
mainpage = "RLCraft_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
