[en]
origins_label = "Pressure Fandom Wikis"
destination = "Pressure Wiki"
destination_base_url = "urbanshade.org"
destination_platform = "mediawiki"
destination_icon = "pressurewiki.png"
destination_main_page = "Pressure_Wiki"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"
destination_host = "Miraheze"
tags = [
    "official",
]

[[en.origins]]
origin = "Pressure Fandom Wiki"
origin_base_url = "pressure.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Pressure_Wiki"

[[en.origins]]
origin = "Pressure Roblox Fandom Wiki"
origin_base_url = "pressure-roblox.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Pressure_Wiki"
