[en]
name = "Pressure"
icon = "pressurewiki.png"

[[en.origin]]
name = "Pressure Fandom Wiki"
url = "pressure.fandom.com"
mainpage = "Pressure_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Pressure Roblox Fandom Wiki"
url = "pressure-roblox.fandom.com"
mainpage = "Pressure_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Pressure Wiki"
host = "Miraheze"
url = "urbanshade.org"
platform = "mediawiki"
icon = "pressurewiki.png"
mainpage = "Pressure_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
