[en]
name = "Arsenal"
icon = "arsenalwiki.png"

[[en.origin]]
name = "Arsenal Fandom Wiki"
url = "robloxarsenal.fandom.com"
mainpage = "Arsenal_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Arsenal Wiki"
host = "Miraheze"
url = "arsenal.miraheze.org"
platform = "mediawiki"
icon = "arsenalwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
