[en]
name = "Roller Coaster"
icon = "coasterpedia.png"

[[en.origin]]
name = "Roller Coaster Fandom Wiki"
url = "rollercoaster.fandom.com"
mainpage = "Roller_Coaster_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Coasterpedia"
url = "coasterpedia.net"
platform = "mediawiki"
icon = "coasterpedia.png"
mainpage = "Coasterpedia_The_Roller_Coaster_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
