[en]
name = "Roots of Pacha"
icon = "rootsofpachawiki.png"

[[en.origin]]
name = "Roots of Pacha Fandom Wiki"
url = "rootsofpacha.fandom.com"
mainpage = "Roots_of_Pacha_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Roots of Pacha Wiki"
host = "wiki.gg"
url = "rootsofpacha.wiki.gg"
platform = "mediawiki"
icon = "rootsofpachawiki.png"
mainpage = "Roots_of_Pacha_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
