[en]
name = "RuneScape Classic"
icon = "runescapeclassic.png"

[[en.origin]]
name = "RuneScape Classic Fandom Wiki"
url = "runescapeclassic.fandom.com"
mainpage = "RuneScape_Classic_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "RuneScape Classic Wiki"
url = "classic.runescape.wiki"
platform = "mediawiki"
icon = "runescapeclassic.png"
mainpage = "RuneScape_Classic_Wiki"
search-path = "/"
content-path = "/w/"
tags = [
    "official",
]
