[en]
name = "SaGa"
icon = "sagawiki.png"

[[en.origin]]
name = "SaGa Fandom Wiki"
url = "saga.fandom.com"
mainpage = "SaGa_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "SaGa Wiki"
url = "sagawiki.org"
platform = "mediawiki"
icon = "sagawiki.png"
mainpage = "SaGa_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
