[en]
name = "Sailor Moon"
icon = "wikimoon.png"

[[en.origin]]
name = "Sailor Moon Fandom Wiki"
url = "sailormoon.fandom.com"
mainpage = "Sailor_Moon_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "WikiMoon"
url = "wikimoon.org"
platform = "mediawiki"
icon = "wikimoon.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/index.php/"
tags = [
    "recommended",
]
