[en]
origins_label = "Saints Row Fandom Wiki"
destination = "Saints Row Wiki"
destination_base_url = "saintsrow.wiki"
destination_platform = "mediawiki"
destination_icon = "saintsrowwiki.png"
destination_content_path = "/wiki/"
destination_search_path = "/w/index.php"
destination_main_page = "Saints_Row_Wiki"

[[en.origins]]
origin = "Saints Row Fandom Wiki"
origin_base_url = "saintsrow.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Saints_Row_Wiki"
