[en]
name = "Salem MMO"
icon = "salemwiki.png"

[[en.origin]]
name = "Salem MMO Fandom Wiki"
url = "salemcraftingmmo.fandom.com"
mainpage = "Salem_-_The_Crafting_MMO_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Salem Wiki"
url = "salemthegame.wiki"
platform = "mediawiki"
icon = "salemwiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/page/"
tags = [
    "recommended",
]
