[en]
name = "Sanrio"
icon = "sanriowiki.png"

[[en.origin]]
name = "Sanrio Fandom Wiki"
url = "sanrio.fandom.com"
mainpage = "Sanrio_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Sanrio Wiki"
url = "sanriowiki.com"
platform = "mediawiki"
icon = "sanriowiki.png"
mainpage = "Sanrio_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
