[en]
name = "Satisfactory"
icon = "satisfactorywiki.png"

[[en.origin]]
name = "Satisfactory Fandom Wiki"
url = "satisfactory.fandom.com"
mainpage = "Satisfactory_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Satisfactory Wiki"
host = "wiki.gg"
url = "satisfactory.wiki.gg"
platform = "mediawiki"
icon = "satisfactorywiki.png"
mainpage = "Satisfactory_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]

[fr]
name = "Satisfactory"
icon = "satisfactorywiki.png"

[[fr.origin]]
name = "Satisfactory Fandom Wiki"
url = "satisfactory.fandom.com/fr"
mainpage = "Satisfactory_Wiki"
content-path = "/wiki/"

[[fr.destination]]
name = "Satisfactory Wiki"
host = "wiki.gg"
url = "satisfactory.wiki.gg/fr"
platform = "mediawiki"
icon = "satisfactorywiki.png"
mainpage = "Satisfactory_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
