[en]
name = "Scav Prototype"
icon = "scavprototypewiki.png"

[[en.origin]]
name = "Scav Prototype Fandom Wiki"
url = "scavprototype.fandom.com"
mainpage = "Scav_Prototype_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Scav Prototype Wiki"
host = "wiki.gg"
url = "scavprototype.wiki.gg"
platform = "mediawiki"
icon = "scavprototypewiki.png"
mainpage = "Scav_Prototype_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
