[ru]
origins_label = "SCP: Secret Laboratory Fandom Wiki"
destination = "SCP: Secret Laboratory Wiki"
destination_base_url = "ru.scpslgame.com"
destination_platform = "mediawiki"
destination_icon = "scpslwiki.png"
destination_main_page = "Заглавная_страница"
destination_search_path = "/index.php"
destination_content_path = "/index.php?title="
tags = [
    "official",
]

[[ru.origins]]
origin = "SCP: Secret Laboratory Fandom Wiki"
origin_base_url = "scp-secret-laboratory.fandom.com/ru"
origin_content_path = "/wiki/"
origin_main_page = "SCP:_Secret_Laboratory_вики"

[en]
origins_label = "SCP: Secret Laboratory Fandom Wiki"
destination = "SCP: Secret Laboratory Wiki"
destination_base_url = "en.scpslgame.com"
destination_platform = "mediawiki"
destination_icon = "scpslwiki.png"
destination_main_page = "Main_Page"
destination_search_path = "/index.php"
destination_content_path = "/index.php?title="
tags = [
    "official",
]

[[en.origins]]
origin = "SCP: Secret Laboratory Fandom Wiki"
origin_base_url = "scp-secret-laboratory.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "SCP:_Secret_Laboratory_Official_Wiki"
