[ru]
name = "SCP: Secret Laboratory"
icon = "scpslwiki.png"

[[ru.origin]]
name = "SCP: Secret Laboratory Fandom Wiki"
url = "scp-secret-laboratory.fandom.com/ru"
mainpage = "SCP:_Secret_Laboratory_вики"
content-path = "/wiki/"

[[ru.destination]]
name = "SCP: Secret Laboratory Wiki"
url = "ru.scpslgame.com"
platform = "mediawiki"
icon = "scpslwiki.png"
mainpage = "Заглавная_страница"
search-path = "/index.php"
content-path = "/index.php?title="
tags = [
    "official",
    "recommended",
]

[en]
name = "SCP: Secret Laboratory"
icon = "scpslwiki.png"

[[en.origin]]
name = "SCP: Secret Laboratory Fandom Wiki"
url = "scp-secret-laboratory.fandom.com"
mainpage = "SCP:_Secret_Laboratory_Official_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "SCP: Secret Laboratory Wiki"
url = "en.scpslgame.com"
platform = "mediawiki"
icon = "scpslwiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/index.php?title="
tags = [
    "official",
    "recommended",
]
