[en]
origins_label = "Scrabdackle Fandom Wiki"
destination = "Scrabdackle Wiki"
destination_base_url = "scrabdackle.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "scrabdacklewiki.png"
destination_main_page = "Scrabdackle_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Scrabdackle Fandom Wiki"
origin_base_url = "scrabdackle.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Scrabdackle_Wiki"
