[en]
name = "Sea of Thieves"
icon = "seaofthieveswiki.png"

[[en.origin]]
name = "Sea of Thieves Fandom Wiki"
url = "seaofthieves.fandom.com"
mainpage = "Sea_of_Thieves_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Sea of Thieves Wiki"
host = "wiki.gg"
url = "seaofthieves.wiki.gg"
platform = "mediawiki"
icon = "seaofthieveswiki.png"
mainpage = "Sea_of_Thieves_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
