[en]
name = "Serial Experiments Lain"
icon = "serialexperimentslainwiki.png"

[[en.origin]]
name = "Serial Experiments Lain Fandom Wiki"
url = "lain.fandom.com"
mainpage = "Serial_Experiments_Lain_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Serial Experiments Lain Wiki"
url = "lain.wiki"
platform = "mediawiki"
icon = "serialexperimentslainwiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
