[en]
name = "Shiny Colors"
icon = "shinycolorswiki.png"

[[en.origin]]
name = "Shiny Colors Fandom Wiki"
url = "shinycolors.fandom.com"
mainpage = "Shiny_Colors_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Shiny Colors Wiki"
url = "shinycolors.wiki"
platform = "mediawiki"
icon = "shinycolorswiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
