[en]
name = "Shroud of the Avatar"
icon = "sotawiki.png"

[[en.origin]]
name = "Shroud of the Avatar Fandom Wiki"
url = "shroudoftheavatar.fandom.com"
mainpage = "Shroud_of_the_Avatar_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "SotAwiki"
url = "sotawiki.net"
platform = "mediawiki"
icon = "sotawiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/sota/"
