[en]
name = "SIGNALIS"
icon = "signalis.png"

[[en.origin]]
name = "SIGNALIS Fandom Wiki"
url = "signalis.fandom.com"
mainpage = "SIGNALIS_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "SIGNALIS Wiki"
host = "wiki.gg"
url = "signalis.wiki.gg"
platform = "mediawiki"
icon = "signalis.png"
mainpage = "SIGNALIS_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
