[en]
name = "Super Lesbian Animal RPG"
icon = "superlesbiananimalrpgwiki.png"

[[en.origin]]
name = "Super Lesbian Animal RPG Fandom Wiki"
url = "slarpg.fandom.com"
mainpage = "Super_Lesbian_Animal_RPG_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Super Lesbian Animal RPG Wiki"
host = "wiki.gg"
url = "slarpg.wiki.gg"
platform = "mediawiki"
icon = "superlesbiananimalrpgwiki.png"
mainpage = "Super_Lesbian_Animal_RPG_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
