[en]
origins_label = "Sly Cooper Fandom Wiki"
destination = "Sly Cooper Wiki"
destination_base_url = "slycooper.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "slycooperwiki.png"
destination_content_path = "/wiki/"
destination_search_path = "/index.php"
destination_main_page = "Sly_Cooper_Wiki"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Sly Cooper Fandom Wiki"
origin_base_url = "slycooper.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Sly_Cooper_Wiki:Main_page"
