[en]
name = "Sly Cooper"
icon = "slycooperwiki.png"

[[en.origin]]
name = "Sly Cooper Fandom Wiki"
url = "slycooper.fandom.com"
mainpage = "Sly_Cooper_Wiki:Main_page"
content-path = "/wiki/"

[[en.destination]]
name = "Sly Cooper Wiki"
host = "wiki.gg"
url = "slycooper.wiki.gg"
platform = "mediawiki"
icon = "slycooperwiki.png"
mainpage = "Sly_Cooper_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
