[en]
name = "Sons of Valhalla"
icon = "sonsofvalhallawiki.png"

[[en.origin]]
name = "Sons of Valhalla Fandom Wiki"
url = "sons-of-valhalla.fandom.com"
mainpage = "Sons_of_Valhalla_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Sons of Valhalla Wiki"
host = "Hooded Horse"
url = "hoodedhorse.com/wiki/Sons_of_Valhalla"
platform = "mediawiki"
icon = "sonsofvalhallawiki.png"
mainpage = "Sons_of_Valhalla_Official_Wiki"
search-path = "/index.php"
content-path = "/"
tags = [
    "official",
    "recommended",
]
