[en]
name = "Sons of the Forest"
icon = "sonsoftheforestwiki.png"

[[en.origin]]
name = "Sons of the Forest Fandom Wiki"
url = "sonsoftheforest.fandom.com"
mainpage = "Sons_of_the_Forest_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Sons of the Forest Wiki"
host = "wiki.gg"
url = "sonsoftheforest.wiki.gg"
platform = "mediawiki"
icon = "sonsoftheforestwiki.png"
mainpage = "Sons_of_the_Forest_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
