[en]
name = "Soulframe Fextralife Wiki"
icon = "avakotwiki.png"

[[en.origin]]
name = "Soulframe Fextralife Wiki"
url = "soulframe.wiki.fextralife.com"
mainpage = "Soulframe Wiki"
content-path = "/"

[[en.origin]]
name = "Soulframe Fandom Wiki"
url = "soulframe.fandom.com"
mainpage = "Soulframe_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Soulframe Wiki"
url = "wiki.avakot.org"
platform = "mediawiki"
icon = "avakotwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/"
