[en]
name = "Space Engineers"
icon = "spaceengineerswiki.png"

[[en.origin]]
name = "Space Engineers Fandom Wiki"
url = "spaceengineers.fandom.com"
mainpage = "Space_Engineers_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Space Engineers Wiki"
host = "wiki.gg"
url = "spaceengineers.wiki.gg"
platform = "mediawiki"
icon = "spaceengineerswiki.png"
mainpage = "Space_Engineers_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
