[en]
name = "Space Station 13"
icon = "spacestation13wiki.png"

[[en.origin]]
name = "Space Station 13 Fandom Wiki"
url = "spacestation13.fandom.com"
mainpage = "Space_Station_13_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Space Station 13 Wiki"
url = "wiki.ss13.co"
platform = "mediawiki"
icon = "spacestation13wiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/"
