[en]
name = "Space Pioneers"
icon = "spacepioneerswiki.png"

[[en.origin]]
name = "Space Pioneers Fandom Wiki"
url = "space-pioneers.fandom.com"
mainpage = "Space_Pioneers_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Space Pioneers Wiki"
host = "Miraheze"
url = "spacepioneers.miraheze.org"
platform = "mediawiki"
icon = "spacepioneerswiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
