[es]
origins_label = "Splatoon Fandom Wiki"
destination = "Inkipedia ES"
destination_base_url = "es.splatoonwiki.org"
destination_platform = "mediawiki"
destination_icon = "inkipedia.png"
destination_main_page = "Página_principal"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"

[[es.origins]]
origin = "Splatoon Fandom Wiki"
origin_base_url = "splatoon.fandom.com/es"
origin_content_path = "/wiki/"
origin_main_page = "Splatoon_Wiki"

[en]
origins_label = "Splatoon Fandom Wiki"
destination = "Inkipedia"
destination_base_url = "splatoonwiki.org"
destination_platform = "mediawiki"
destination_icon = "inkipedia.png"
destination_main_page = "Main_Page"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"

[[en.origins]]
origin = "Splatoon Fandom Wiki"
origin_base_url = "splatoon.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Splatoon_Wiki"

[fr]
origins_label = "Splatoon Fandom Wiki"
destination = "Inkipédia"
destination_base_url = "fr.splatoonwiki.org"
destination_platform = "mediawiki"
destination_icon = "inkipedia.png"
destination_main_page = "Accueil"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"

[[fr.origins]]
origin = "Splatoon Fandom Wiki"
origin_base_url = "splatoon.fandom.com/fr"
origin_content_path = "/wiki/"
origin_main_page = "Wiki_Splatoon"
