[en]
name = "Spyro"
icon = "spyro.png"

[[en.origin]]
name = "Spyro Fandom Wiki"
url = "spyro.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.origin]]
name = "Spyro Neoseeker Wiki"
url = "spyro.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Spyro Wiki"
url = "spyrowiki.com"
platform = "mediawiki"
icon = "spyro.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
