[en]
origins_label = "Spyro Fandom & Neoseeker Wikis"
destination = "Spyro Wiki"
destination_base_url = "spyrowiki.com"
destination_platform = "mediawiki"
destination_icon = "spyro.png"
destination_main_page = "Main_Page"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"

[[en.origins]]
origin = "Spyro Fandom Wiki"
origin_base_url = "spyro.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Main_Page"

[[en.origins]]
origin = "Spyro Neoseeker Wiki"
origin_base_url = "spyro.neoseeker.com"
origin_content_path = "/wiki/"
origin_main_page = "Main_Page"
