[it]
name = "Memory Alpha"
icon = "wikitrek.png"

[[it.origin]]
name = "Memory Alpha Fandom Wiki"
url = "memory-alpha.fandom.com/it"
mainpage = "Pagina_principale"
content-path = "/wiki/"

[[it.destination]]
name = "WikiTrek"
url = "wikitrek.org"
platform = "mediawiki"
icon = "wikitrek.png"
mainpage = "Pagina_principale"
search-path = "/wt/index.php"
content-path = "/wiki/"
