[tr]
name = "Star Wars"
icon = "sithpedi.png"

[[tr.origin]]
name = "Star Wars Fandom Wiki"
url = "starwars.fandom.com/tr"
mainpage = "Ana_sayfa"
content-path = "/wiki/"

[[tr.destination]]
name = "Sithpedi"
url = "starwarsturkiye.com"
platform = "mediawiki"
icon = "sithpedi.png"
mainpage = "Anasayfa"
search-path = "/wiki/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]

[fi]
name = "Jedipedia"
icon = "jedipedia.png"

[[fi.origin]]
name = "Jedipedia Fandom Wiki"
url = "starwars.fandom.com/fi"
mainpage = "Etusivu"
content-path = "/wiki/"

[[fi.destination]]
name = "Jedipedia"
host = "ShoutWiki"
url = "www.jedipedia.fi"
platform = "mediawiki"
icon = "jedipedia.png"
mainpage = "Etusivu"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
