[en]
name = "Starfy"
icon = "starfy.png"

[[en.origin]]
name = "Starfy Fandom Wiki"
url = "starfy.fandom.com"
mainpage = "Starfy_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Starfy Wiki"
url = "www.starfywiki.org"
platform = "mediawiki"
icon = "starfy.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
