[de]
name = "Stardew Valley"
icon = "stardewvalley.png"

[[de.origin]]
name = "Stardew Valley Fandom Wiki"
url = "stardewvalley.fandom.com/de"
mainpage = "Stardew_Valley_Wiki"
content-path = "/wiki/"

[[de.destination]]
name = "Stardew Valley Wiki"
url = "de.stardewvalleywiki.com"
platform = "mediawiki"
icon = "stardewvalley.png"
mainpage = "Stardew_Valley_Wiki"
search-path = "/mediawiki/index.php"
content-path = "/"

[es]
name = "Stardew Valley"
icon = "stardewvalley.png"

[[es.origin]]
name = "Stardew Valley Fandom Wiki"
url = "stardewvalley.fandom.com/es"
mainpage = "Wikia_Stardew_Valley"
content-path = "/wiki/"

[[es.destination]]
name = "Stardew Valley Wiki"
url = "es.stardewvalleywiki.com"
platform = "mediawiki"
icon = "stardewvalley.png"
mainpage = "Stardew_Valley_Wiki"
search-path = "/mediawiki/index.php"
content-path = "/"

[en]
name = "Stardew Valley"
icon = "stardew.png"

[[en.origin]]
name = "Stardew Valley Fandom Wiki"
url = "stardewvalley.fandom.com"
mainpage = "Stardew_Valley_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Stardew Valley Wiki"
url = "stardewvalleywiki.com"
platform = "mediawiki"
icon = "stardew.png"
mainpage = "Stardew_Valley_Wiki"
search-path = "/mediawiki/index.php"
content-path = "/"
tags = [
    "official",
]

[fr]
name = "Stardew Valley"
icon = "stardewvalleywiki.png"

[[fr.origin]]
name = "Stardew Valley Fandom Wiki"
url = "stardew-valley-fr.fandom.com/fr"
mainpage = "Home"
content-path = "/wiki/"

[[fr.destination]]
name = "Stardew Valley Wiki"
url = "fr.stardewvalleywiki.com"
platform = "mediawiki"
icon = "stardewvalleywiki.png"
mainpage = "Stardew_Valley_Wiki"
search-path = "/mediawiki/index.php"
content-path = "/"
tags = [
    "official",
]
