[en]
name = "StarSector"
icon = "starsectorwiki.png"

[[en.origin]]
name = "StarSector Fandom Wiki"
url = "starsector.fandom.com"
mainpage = "Starsector_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Starsector Wiki"
host = "wiki.gg"
url = "starsector.wiki.gg"
platform = "mediawiki"
icon = "starsectorwiki.png"
mainpage = "Starsector_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
