[en]
name = "Jorvikpedia"
icon = "starstablewiki.png"

[[en.origin]]
name = "Jorvikpedia Fandom Wiki"
url = "jorvikipedia.fandom.com"
mainpage = "Jorvikpedia_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Star Stable Wiki"
host = "wiki.gg"
url = "starstable.wiki.gg"
platform = "mediawiki"
icon = "starstablewiki.png"
mainpage = "Star_Stable_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
