[de]
origins_label = "Star Citizen Fandom Wiki"
destination = "Star Citizen Wiki"
destination_base_url = "star-citizen.wiki"
destination_platform = "mediawiki"
destination_icon = "starcitizen.png"
destination_main_page = "Star_Citizen_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/"

[[de.origins]]
origin = "Star Citizen Fandom Wiki"
origin_base_url = "starcitizen.fandom.com/de"
origin_content_path = "/wiki/"
origin_main_page = "Star_Citizen_Wiki"

[en]
origins_label = "Star Citizen Fandom Wiki"
destination = "Star Citizen Wiki"
destination_base_url = "starcitizen.tools"
destination_platform = "mediawiki"
destination_icon = "starcitizen.png"
destination_main_page = "Star_Citizen_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/"

[[en.origins]]
origin = "Star Citizen Fandom Wiki"
origin_base_url = "starcitizen.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Star_Citizen_Wiki"
