[en]
name = "SteamWorld"
icon = "steamworldwiki.png"

[[en.origin]]
name = "SteamWorld Fandom Wiki"
url = "steamworld.fandom.com"
mainpage = "SteamWorld_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "SteamWorld Wiki"
host = "wiki.gg"
url = "steamworld.wiki.gg"
platform = "mediawiki"
icon = "steamworldwiki.png"
mainpage = "SteamWorld_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
