[en]
name = "Strinova"
icon = "strinova.png"

[[en.origin]]
name = "Strinova Fandom Wiki"
url = "strinova.fandom.com"
mainpage = "Strinova_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Strinova Wiki"
host = "Miraheze"
url = "strinova.org"
platform = "mediawiki"
icon = "strinova.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
