[en]
name = "Suikoden"
icon = "gensopedia.png"

[[en.origin]]
name = "Suikoden Fandom Wiki"
url = "suikoden.fandom.com"
mainpage = "Suikoden_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Gensopedia"
url = "gensopedia.org"
platform = "mediawiki"
icon = "gensopedia.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/w/"
tags = [
    "recommended",
]
