[en]
name = "Sun Haven"
icon = "sunhavenwiki.png"

[[en.origin]]
name = "Sun Haven Fandom Wiki"
url = "sun-haven.fandom.com"
mainpage = "Sun_Haven_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Sun Haven Wiki"
host = "wiki.gg"
url = "sunhaven.wiki.gg"
platform = "mediawiki"
icon = "sunhavenwiki.png"
mainpage = "Sun_Haven_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
