[en]
name = "Sunkenland"
icon = "sunkenlandwiki.png"

[[en.origin]]
name = "Sunkenland Fandom Wiki"
url = "sunkenland.fandom.com"
mainpage = "Sunkenland_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Sunkenland Wiki"
host = "wiki.gg"
url = "sunkenland.wiki.gg"
platform = "mediawiki"
icon = "sunkenlandwiki.png"
mainpage = "Sunkenland_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
