[en]
name = "Sunless Sea"
icon = "sunlessseawiki.png"

[[en.origin]]
name = "Sunless Sea Fandom Wiki"
url = "sunlesssea.fandom.com"
mainpage = "Sunless_Sea_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Sunless Sea Wiki"
host = "Miraheze"
url = "sunlesssea.miraheze.org"
platform = "mediawiki"
icon = "sunlessseawiki.png"
mainpage = "Official_Sunless_Sea_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
