[en]
name = "Sunless Skies"
icon = "sunlessskieswiki.png"

[[en.origin]]
name = "Sunless Skies Fandom Wiki"
url = "sunlessskies.fandom.com"
mainpage = "Sunless_Skies_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Sunless Skies Wiki"
host = "Miraheze"
url = "sunlessskies.miraheze.org"
platform = "mediawiki"
icon = "sunlessskieswiki.png"
mainpage = "Official_Sunless_Skies_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
