[es]
name = "Smashpedia"
icon = "smashpedia.png"

[[es.origin]]
name = "Smashpedia Fandom Wiki"
url = "supersmashbros.fandom.com/es"
mainpage = "Smashpedia"
content-path = "/wiki/"

[[es.destination]]
name = "SmashPedia"
url = "es.ssbwiki.com"
platform = "mediawiki"
icon = "smashpedia.png"
mainpage = "SmashPedia"
search-path = "/index.php"
content-path = "/wiki/"

[en]
name = "Super Smash Bros."
icon = "smashwiki.png"

[[en.origin]]
name = "Super Smash Bros. Fandom Wiki"
url = "supersmashbros.fandom.com"
mainpage = "Smashpedia"
content-path = "/wiki/"

[[en.origin]]
name = "Smash Bros Wiki - Neoseeker"
url = "smashbros.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "SmashWiki"
url = "www.ssbwiki.com"
platform = "mediawiki"
icon = "smashwiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/"
