[es]
name = "Team Fortress"
icon = "teamfortress.png"

[[es.origin]]
name = "Team Fortress Fandom Wiki"
url = "team-fortress.fandom.com/es"
mainpage = "Wiki_Team_Fortress"
content-path = "/wiki/"

[[es.destination]]
name = "Team Fortress Wiki"
url = "wiki.teamfortress.com"
platform = "mediawiki"
icon = "teamfortress.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
content-suffix = "/es"
tags = [
    "official",
    "recommended",
]

[en]
name = "Team Fortress"
icon = "teamfortress.png"

[[en.origin]]
name = "Team Fortress Fandom Wiki"
url = "teamfortress.fandom.com"
mainpage = "Team_Fortress_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Team Fortress Wiki"
url = "wiki.teamfortress.com"
platform = "mediawiki"
icon = "teamfortress.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]

[pt]
name = "Team Fortress"
icon = "teamfortress.png"

[[pt.origin]]
name = "Team Fortress Fandom Wiki"
url = "team-fortress.fandom.com/pt-br"
mainpage = "Página_principal"
content-path = "/wiki/"

[[pt.destination]]
name = "Team Fortress Wiki"
url = "wiki.teamfortress.com"
platform = "mediawiki"
icon = "teamfortress.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
content-suffix = "/pt-br"
tags = [
    "official",
    "recommended",
]

[pl]
name = "Team Fortress"
icon = "teamfortress.png"

[[pl.origin]]
name = "Team Fortress Fandom Wiki"
url = "teamfortress.fandom.com/pl"
mainpage = "Team_Fortress_Wiki"
content-path = "/wiki/"

[[pl.destination]]
name = "Team Fortress Wiki"
url = "wiki.teamfortress.com"
platform = "mediawiki"
icon = "teamfortress.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
content-suffix = "/pl"
tags = [
    "official",
    "recommended",
]
