[en]
name = "Tempest Rising"
icon = "tempestrisingwiki.png"

[[en.origin]]
name = "Tempest Rising Fandom Wiki"
url = "tempestrising.fandom.com"
mainpage = "Tempest_Rising_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Tempest Rising Wiki"
host = "wiki.gg"
url = "tempestrising.wiki.gg"
platform = "mediawiki"
icon = "tempestrisingwiki.png"
mainpage = "Tempest_Rising_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
