[en]
name = "Temtem"
icon = "officialtemtemwiki.png"

[[en.origin]]
name = "Temtem Fandom Wiki"
url = "temtem.fandom.com"
mainpage = "Temtem_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Temtem Wiki"
host = "wiki.gg"
url = "temtem.wiki.gg"
platform = "mediawiki"
icon = "officialtemtemwiki.png"
mainpage = "Temtem_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]

[fr]
name = "Temtem"
icon = "temtem.png"

[[fr.origin]]
name = "Temtem Fandom Wiki"
url = "temtem.fandom.com/fr"
mainpage = "Temtem_Wiki"
content-path = "/wiki/"

[[fr.destination]]
name = "Temtem Wiki"
host = "wiki.gg"
url = "temtem.wiki.gg/fr"
platform = "mediawiki"
icon = "temtem.png"
mainpage = "Temtem_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
