[de]
name = "Terraria"
icon = "terrariawiki.png"

[[de.origin]]
name = "Terraria Fandom Wiki"
url = "terraria.fandom.com/de"
mainpage = "Terraria_Wiki"
content-path = "/wiki/"

[[de.destination]]
name = "Terraria Wiki"
host = "wiki.gg"
url = "terraria.wiki.gg/de"
platform = "mediawiki"
icon = "terrariawiki.png"
mainpage = "Terraria_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[ru]
name = "Terraria"
icon = "terrariawiki.png"

[[ru.origin]]
name = "Terraria Fandom Wiki"
url = "terraria.fandom.com/ru"
mainpage = "Terraria_Wiki"
content-path = "/wiki/"

[[ru.destination]]
name = "Terraria Wiki"
host = "wiki.gg"
url = "terraria.wiki.gg/ru"
platform = "mediawiki"
icon = "terrariawiki.png"
mainpage = "Terraria_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[es]
name = "Terraria"
icon = "terrariawiki.png"

[[es.origin]]
name = "Terraria Fandom Wiki"
url = "terraria.fandom.com/es"
mainpage = "Wiki_Terraria"
content-path = "/wiki/"

[[es.destination]]
name = "Terraria Wiki"
host = "wiki.gg"
url = "terraria.wiki.gg/es"
platform = "mediawiki"
icon = "terrariawiki.png"
mainpage = "Terraria_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[en]
name = "Terraria"
icon = "terrariawiki.png"

[[en.origin]]
name = "Terraria Fandom Wiki"
url = "terraria.fandom.com"
mainpage = "Terraria_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Terraria Fandom Wiki (Archived)"
url = "terraria-archive.fandom.com"
mainpage = "Terraria_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Terraria Wiki - Neoseeker"
url = "terraria.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Terraria Wiki"
host = "wiki.gg"
url = "terraria.wiki.gg"
platform = "mediawiki"
icon = "terrariawiki.png"
mainpage = "Terraria_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[pt]
name = "Terraria"
icon = "terrariawiki.png"

[[pt.origin]]
name = "Terraria Fandom Wiki"
url = "terraria.fandom.com/pt"
mainpage = "Terraria_Wiki"
content-path = "/wiki/"

[[pt.destination]]
name = "Terraria Wiki"
host = "wiki.gg"
url = "terraria.wiki.gg/pt"
platform = "mediawiki"
icon = "terrariawiki.png"
mainpage = "Terraria_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[pl]
name = "Terraria"
icon = "terrariawiki.png"

[[pl.origin]]
name = "Terraria Fandom Wiki"
url = "terraria.fandom.com/pl"
mainpage = "Terraria_Wiki"
content-path = "/wiki/"

[[pl.destination]]
name = "Terraria Wiki"
host = "wiki.gg"
url = "terraria.wiki.gg/pl"
platform = "mediawiki"
icon = "terrariawiki.png"
mainpage = "Terraria_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[ko]
name = "Terraria"
icon = "terrariawiki.png"

[[ko.origin]]
name = "Terraria Fandom Wiki"
url = "terraria.fandom.com/ko"
mainpage = "Terraria_Wiki"
content-path = "/wiki/"

[[ko.destination]]
name = "Terraria Wiki"
host = "wiki.gg"
url = "terraria.wiki.gg/ko"
platform = "mediawiki"
icon = "terrariawiki.png"
mainpage = "Terraria_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[zh]
name = "Terraria"
icon = "terrariawiki.png"

[[zh.origin]]
name = "Terraria Fandom Wiki"
url = "terraria.fandom.com/zh"
mainpage = "Terraria_Wiki"
content-path = "/wiki/"

[[zh.destination]]
name = "Terraria Wiki"
host = "wiki.gg"
url = "terraria.wiki.gg/zh"
platform = "mediawiki"
icon = "terrariawiki.png"
mainpage = "Terraria_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[hu]
name = "Terraria"
icon = "terrariawiki.png"

[[hu.origin]]
name = "Terraria Fandom Wiki"
url = "terraria.fandom.com/hu"
mainpage = "Terraria_Wiki"
content-path = "/wiki/"

[[hu.destination]]
name = "Terraria Wiki"
host = "wiki.gg"
url = "terraria.wiki.gg/hu"
platform = "mediawiki"
icon = "terrariawiki.png"
mainpage = "Terraria_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[fr]
name = "Terraria"
icon = "terrariawiki.png"

[[fr.origin]]
name = "Terraria Fandom Wiki"
url = "terraria.fandom.com/fr"
mainpage = "Terraria_Wiki"
content-path = "/wiki/"

[[fr.destination]]
name = "Terraria Wiki"
host = "wiki.gg"
url = "terraria.wiki.gg/fr"
platform = "mediawiki"
icon = "terrariawiki.png"
mainpage = "Terraria_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]

[uk]
name = "Terraria"
icon = "terrariawiki.png"

[[uk.origin]]
name = "Terraria Fandom Wiki"
url = "terraria.fandom.com/uk"
mainpage = "Terraria_Wiki"
content-path = "/wiki/"

[[uk.destination]]
name = "Terraria Wiki"
host = "wiki.gg"
url = "terraria.wiki.gg/uk"
platform = "mediawiki"
icon = "terrariawiki.png"
mainpage = "Terraria_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
