[en]
name = "Discworld"
icon = "terrypratchettwiki.png"

[[en.origin]]
name = "Discworld Fandom Wiki"
url = "discworld.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Terry Pratchett Wiki"
url = "wiki.lspace.org"
platform = "mediawiki"
icon = "terrypratchettwiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/"
tags = [
    "recommended",
]
