[en]
name = "The Broken Script"
icon = "thebrokenscriptwiki.png"

[[en.origin]]
name = "The Broken Script Fandom Wiki"
url = "the-broken-script.fandom.com"
mainpage = "The_Broken_Script_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "The Broken Script Wiki"
host = "wiki.gg"
url = "thebrokenscript.wiki.gg"
platform = "mediawiki"
icon = "thebrokenscriptwiki.png"
mainpage = "The_Broken_Script_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
