[en]
name = "The Celestial Caverns"
icon = "thecelestialcavernswiki.png"

[[en.origin]]
name = "The Celestial Caverns Fandom Wiki"
url = "the-celestial-caverns.fandom.com"
mainpage = "The_Celestial_Caverns_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "The Celestial Caverns Wiki"
host = "Miraheze"
url = "thecelestialcaverns.miraheze.org"
platform = "mediawiki"
icon = "thecelestialcavernswiki.png"
mainpage = "The_Celestial_Caverns_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
