[en]
name = "The Cycle: Frontier"
icon = "tcfwiki.png"

[[en.origin]]
name = "The Cycle: Frontier Fandom Wiki"
url = "thecyclefrontier.fandom.com"
mainpage = "The_Cycle_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "The Cycle: Frontier Wiki"
url = "thecyclefrontier.wiki"
platform = "mediawiki"
icon = "tcfwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
