[en]
name = "THE FINALS"
icon = "thefinalswiki.png"

[[en.origin]]
name = "THE FINALS Fandom Wiki"
url = "the-finals.fandom.com"
mainpage = "THE_FINALS_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "THE FINALS Wiki"
url = "www.thefinals.wiki"
platform = "mediawiki"
icon = "thefinalswiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
