[en]
origins_label = "The Matchless Kungfu Fandom Wiki"
destination = "The Matchless Kungfu Wiki"
destination_base_url = "thematchlesskungfu.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "thematchlesskungfuwiki.png"
destination_main_page = "The_Matchless_Kungfu_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "The Matchless Kungfu Fandom Wiki"
origin_base_url = "the-matchless-kungfu.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "The_Matchless_Kungfu_Wiki"
