[en]
name = "The Wandering Inn"
icon = "thewanderinginnwiki.png"

[[en.origin]]
name = "The Wandering Inn Fandom Wiki"
url = "thewanderinginn.fandom.com"
mainpage = "The_Wandering_Inn_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "The Wandering Inn Wiki"
url = "wiki.wanderinginn.com"
platform = "mediawiki"
icon = "thewanderinginnwiki.png"
mainpage = "The_Wandering_Inn_Wiki"
search-path = "/index.php"
content-path = "/"
tags = [
    "official",
    "recommended",
]
