[en]
name = "The World Ends with You"
icon = "thewikiendswithyou.png"

[[en.origin]]
name = "The World Ends with You Fandom Wiki"
url = "twewy.fandom.com"
mainpage = "The_World_Ends_with_You_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "The World Ends with You Wiki"
url = "twewy.wiki"
platform = "mediawiki"
icon = "thewikiendswithyou.png"
mainpage = "The_World_Ends_with_You_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
