[en]
name = "TheyMightBeGiants"
icon = "thismightbeawiki.png"

[[en.origin]]
name = "TheyMightBeGiants Fandom Wiki"
url = "theymightbegiants.fandom.com"
mainpage = "TheyMightBeGiants_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "This Might Be A Wiki"
url = "tmbw.net"
platform = "mediawiki"
icon = "thismightbeawiki.png"
mainpage = "Main_Page"
search-path = "/wiki/index.php"
content-path = "/wiki/"
