[en]
name = "Timespinner"
icon = "timespinnerwiki.png"

[[en.origin]]
name = "Timespinner Fandom Wiki"
url = "timespinner.fandom.com"
mainpage = "Timespinner_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Timespinner Wiki"
url = "timespinnerwiki.com"
platform = "mediawiki"
icon = "timespinnerwiki.png"
mainpage = "Timespinner_Wiki"
search-path = "/mediawiki/index.php"
content-path = "/"
tags = [
    "recommended",
]
