[en]
origins_label = "Tin Can Fandom Wiki"
destination = "Tin Can Wiki"
destination_base_url = "tincan.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "tincanwiki.png"
destination_main_page = "Tin_Can_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[en.origins]]
origin = "Tin Can Fandom Wiki"
origin_base_url = "tincan.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Tin_Can_Wiki"
