[en]
origins_label = "Tiny Rogues Fandom Wiki"
destination = "Tiny Rogues Wiki"
destination_base_url = "roguepedia.net"
destination_platform = "mediawiki"
destination_icon = "tinyrogueswiki.png"
destination_main_page = "Main_Page"
destination_search_path = "/wiki/index.php"
destination_content_path = "/w/"

[[en.origins]]
origin = "Tiny Rogues Fandom Wiki"
origin_base_url = "tiny-rogues.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Tiny_Rogues_Wiki"
