[en]
name = "Titanfall"
icon = "titanfallwiki.png"

[[en.origin]]
name = "Titanfall Fandom Wiki"
url = "titanfall.fandom.com"
mainpage = "Titanfall_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Titanfall Wiki"
host = "wiki.gg"
url = "titanfall.wiki.gg"
platform = "mediawiki"
icon = "titanfallwiki.png"
mainpage = "Titanfall_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
