[en]
origins_label = "Toontown Fandom Wiki"
destination = "Toontown Wiki"
destination_base_url = "toontown.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "toontown.png"
destination_main_page = "Toontown_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Toontown Fandom Wiki"
origin_base_url = "toontown.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Main_Page"
