[en]
name = "Toontown Corporate Clash"
icon = "toontowncorporateclashwiki.png"

[[en.origin]]
name = "Toontown Corporate Clash Fandom Wiki"
url = "toontown-corporate-clash.fandom.com"
mainpage = "Toontown_Corporate_Clash_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Toontown Corporate Clash Wiki"
host = "wiki.gg"
url = "corporateclash.wiki.gg"
platform = "mediawiki"
icon = "toontowncorporateclashwiki.png"
mainpage = "Toontown_Corporate_Clash_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
