[en]
name = "Toontown"
icon = "toontown.png"

[[en.origin]]
name = "Toontown Fandom Wiki"
url = "toontown.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Toontown Wiki"
host = "wiki.gg"
url = "toontown.wiki.gg"
platform = "mediawiki"
icon = "toontown.png"
mainpage = "Toontown_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
