[en]
name = "Torn City"
icon = "tornwiki.png"

[[en.origin]]
name = "Torn City Fandom Wiki"
url = "torncity.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Torn Wiki"
url = "wiki.torn.com"
platform = "mediawiki"
icon = "tornwiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "official",
    "recommended",
]
