[en]
name = "TowerFall"
icon = "towerfallwiki.png"

[[en.origin]]
name = "TowerFall Fandom Wiki"
url = "towerfall.fandom.com"
mainpage = "TowerFall_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "TowerFall Wiki"
host = "wiki.gg"
url = "towerfall.wiki.gg"
platform = "mediawiki"
icon = "towerfallwiki.png"
mainpage = "TowerFall_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
