[en]
name = "Tower Unite"
icon = "towerunitewiki.png"

[[en.origin]]
name = "Tower Unite Fandom Wiki"
url = "tower-unite.fandom.com"
mainpage = "Tower_Unite_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Tower Unite Wiki"
host = "wiki.gg"
url = "towerunite.wiki.gg"
platform = "mediawiki"
icon = "towerunitewiki.png"
mainpage = "Tower_Unite_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
