[en]
name = "Transformers"
icon = "transformers.png"

[[en.origin]]
name = "Transformers Fandom Wiki"
url = "transformers.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Transformers Wiki"
url = "tfwiki.net"
platform = "mediawiki"
icon = "transformers.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
