[en]
name = "Treasure Adventure Game"
icon = "treasureadventureworldwiki.png"

[[en.origin]]
name = "Treasure Adventure Game Fandom Wiki"
url = "treasureadventuregame.fandom.com"
mainpage = "Treasure_Adventure_Game_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Treasure Adventure World Wiki"
url = "treasureadventurewiki.com"
platform = "mediawiki"
icon = "treasureadventureworldwiki.png"
mainpage = "Treasure_Adventure_Wiki"
search-path = "/mediawiki/index.php"
content-path = "/"
