[en]
name = "Two Worlds"
icon = "twoworldswiki.png"

[[en.origin]]
name = "Two Worlds Fandom Wiki"
url = "twoworlds.fandom.com"
mainpage = "Two_Worlds_Main"
content-path = "/wiki/"

[[en.origin]]
name = "Two Worlds II Fandom Wiki"
url = "tw2.fandom.com"
mainpage = "Two_Worlds_2_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Two Worlds Wiki"
url = "twoworldswiki.com"
platform = "mediawiki"
icon = "twoworldswiki.png"
mainpage = "Two_Worlds_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
