[en]
name = "U.B. Funkeys"
icon = "ubfunkeyswiki.png"

[[en.origin]]
name = "U.B. Funkeys Fandom Wiki"
url = "ubfunkeys.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "U.B. Funkeys Wiki"
url = "ubfunkeys.wiki"
platform = "mediawiki"
icon = "ubfunkeyswiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/index.php?title="
