[en]
name = "UFO 50"
icon = "ufo50.png"

[[en.origin]]
name = "UFO 50 Fandom Wiki"
url = "ufo50.fandom.com"
mainpage = "UFO_50_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "UFO 50 Wiki"
host = "Miraheze"
url = "ufo50.miraheze.org"
platform = "mediawiki"
icon = "ufo50.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
