[en]
name = "Ultima Online"
icon = "uoguide.png"

[[en.origin]]
name = "Ultima Online Fandom Wiki"
url = "ultimaonline.fandom.com"
mainpage = "Ultima_Online_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "UOGuide"
url = "www.uoguide.com"
platform = "mediawiki"
icon = "uoguide.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/"
