[en]
name = "ULTRAKILL"
icon = "ultrawiki.png"

[[en.origin]]
name = "ULTRAKILL Fandom Wiki"
url = "ultrakill.fandom.com"
mainpage = "Home"
content-path = "/wiki/"

[[en.destination]]
name = "ULTRAWIKI"
host = "wiki.gg"
url = "ultrakill.wiki.gg"
platform = "mediawiki"
icon = "ultrawiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
