[en]
name = "Uma Musume"
icon = "umamusumewiki.png"

[[en.origin]]
name = "Uma Musume Fandom Wiki"
url = "umamusume.fandom.com"
mainpage = "Uma_Musume_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Umamusume Wiki"
url = "umamusu.wiki"
platform = "mediawiki"
icon = "umamusumewiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/"
tags = [
    "recommended",
]
