[en]
name = "Uncompromising Mode"
icon = "uncompromisingmodewiki.png"

[[en.origin]]
name = "Uncompromising Mode Fandom Wiki"
url = "uncompromising-mode.fandom.com"
mainpage = "Unrelenting_Mode_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Uncompromising Mode Wiki"
host = "wiki.gg"
url = "uncompromisingmode.wiki.gg"
platform = "mediawiki"
icon = "uncompromisingmodewiki.png"
mainpage = "Uncompromising_Mode_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
