[en]
name = "Undertale Yellow"
icon = "undertaleyellowwiki.png"

[[en.origin]]
name = "Undertale Yellow Fandom Wiki"
url = "undertaleyellow.fandom.com"
mainpage = "Undertale_Yellow_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Undertale Yellow Wiki"
host = "wiki.gg"
url = "undertaleyellow.wiki.gg"
platform = "mediawiki"
icon = "undertaleyellowwiki.png"
mainpage = "Undertale_Yellow_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
