[en]
name = "Universal Union"
icon = "universalunion.png"

[[en.origin]]
name = "Universal Union Fandom Wiki"
url = "universalunion.fandom.com"
mainpage = "MainPage"
content-path = "/wiki/"

[[en.destination]]
name = "Universal Union Wiki"
host = "Miraheze"
url = "universalunion.wiki"
platform = "mediawiki"
icon = "universalunion.png"
mainpage = "Main"
search-path = "/w/index.php"
content-path = "/"
tags = [
    "recommended",
]
