[en]
origins_label = "Unnamed Space Idle Fandom Wiki"
destination = "Unnamed Space Idle Wiki"
destination_base_url = "usi.game-vault.net"
destination_platform = "mediawiki"
destination_icon = "unnamedspaceidle.png"
destination_main_page = "Main_Page"
destination_search_path = "/w/index.php"
destination_content_path = "/wiki/"
tags = [
    "official",
]

[[en.origins]]
origin = "Unnamed Space Idle Fandom Wiki"
origin_base_url = "usi.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "USI_Wiki"
