[en]
origins_label = "Unturned Bunker Fandom Wiki"
destination = "Unturned Wiki"
destination_base_url = "unturned.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "unturnedwiki.png"
destination_main_page = "Unturned_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"
tags = [
    "official",
]

[[en.origins]]
origin = "Unturned Bunker Fandom Wiki"
origin_base_url = "unturned.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Unturned_Bunker_Wiki"
