[en]
name = "Usagi Shima"
icon = "usagishimawiki.png"

[[en.origin]]
name = "Usagi Shima Fandom Wiki"
url = "usagishima.fandom.com"
mainpage = "Usagi_Shima_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Usagi Shima Wiki"
host = "Miraheze"
url = "usagishima.miraheze.org"
platform = "mediawiki"
icon = "usagishimawiki.png"
mainpage = "Usagi_Shima_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
