[en]
name = "Uta no Prince-sama"
icon = "utanoprincesama.png"

[[en.origin]]
name = "Uta no Prince-sama Fandom Wiki"
url = "utanoprincesama.fandom.com"
mainpage = "Uta_no_Prince-sama_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Uta no Prince-sama Wiki"
host = "Miraheze"
url = "utanoprincesama.miraheze.org"
platform = "mediawiki"
icon = "utanoprincesama.png"
mainpage = "Uta_no_Prince-sama_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
