[en]
name = "Vampire Survivors"
icon = "vampiresurvivorswiki.png"

[[en.origin]]
name = "Vampire Survivors Fandom Wiki"
url = "vampire-survivors.fandom.com"
mainpage = "Vampire_Survivors_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Vampire Survivors Wiki"
url = "vampire.survivors.wiki"
platform = "mediawiki"
icon = "vampiresurvivorswiki.png"
mainpage = "Vampire_Survivors_Wiki"
search-path = "/"
content-path = "/w/"
tags = [
    "official",
]
