[en]
name = "Vendetta Online"
icon = "vendettawiki.png"

[[en.origin]]
name = "Vendetta Online Fandom Wiki"
url = "vendetta-online.fandom.com"
mainpage = "Vendetta_Online_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Vendetta Online Wiki"
url = "vo-wiki.com"
platform = "mediawiki"
icon = "vendettawiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
