[en]
name = "Vivid/stasis"
icon = "vividstasiswiki.png"

[[en.origin]]
name = "Vivid/stasis Fandom Wiki"
url = "vividstasis.fandom.com"
mainpage = "Vivid/stasis_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "vivid/stasis wiki"
host = "Miraheze"
url = "vividstasis.miraheze.org"
platform = "mediawiki"
icon = "vividstasiswiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
