[en]
origins_label = "Voices of the Void Fandom Wiki"
destination = "Voices of the Void Wiki"
destination_base_url = "voicesofthevoid.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "voicesofthevoidwiki.png"
destination_main_page = "Voices_of_the_Void_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Voices of the Void Fandom Wiki"
origin_base_url = "votv.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Voices_of_the_Void"
