[en]
name = "Volcano Princess"
icon = "volcanoprincesswiki.png"

[[en.origin]]
name = "Volcano Princess Fandom Wiki"
url = "volcano-princess.fandom.com"
mainpage = "Volcano_Princess_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Volcano Princess Wiki"
host = "Miraheze"
url = "volcanoprincess.miraheze.org"
platform = "mediawiki"
icon = "volcanoprincesswiki.png"
mainpage = "Main_Page"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
