[en]
name = "VTOL VR"
icon = "vtolvr.png"

[[en.origin]]
name = "VTOL VR Fandom Wiki"
url = "vtol-vr.fandom.com"
mainpage = "VTOL_VR_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "VTOL VR Wiki"
host = "wiki.gg"
url = "vtolvr.wiki.gg"
platform = "mediawiki"
icon = "vtolvr.png"
mainpage = "VTOL_VR_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
