[en]
name = "Vylet Pony"
icon = "vyletponywiki.png"

[[en.origin]]
name = "Vylet Pony Fandom Wiki"
url = "vylet-pony.fandom.com"
mainpage = "Vylet_Pony_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Vylet Pony Wiki"
host = "Miraheze"
url = "vylet.wiki"
platform = "mediawiki"
icon = "vyletponywiki.png"
mainpage = "Vylet_Pony_Wiki"
search-path = "/w/index.php"
content-path = "/"
tags = [
    "recommended",
]
