[en]
name = "Wakfu"
icon = "wakfuwiki.png"

[[en.origin]]
name = "Wakfu Fandom Wiki"
url = "wakfu.fandom.com"
mainpage = "Wakfu_Wiki"
content-path = "/wiki/"

[[en.origin]]
name = "Wakfu Neoseeker Wiki"
url = "wakfu.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Wakfu Wiki"
host = "wiki.gg"
url = "wakfu.wiki.gg"
platform = "mediawiki"
icon = "wakfuwiki.png"
mainpage = "Wakfu_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
