[en]
name = "Warcraft"
icon = "warcraftwiki.png"

[[en.origin]]
name = "Wowpedia Fandom Wiki"
url = "wowpedia.fandom.com"
mainpage = "Wowpedia"
content-path = "/wiki/"

[[en.origin]]
name = "WoWWiki Fandom Wiki (Archived)"
url = "wowwiki-archive.fandom.com"
mainpage = "Portal:Main"
content-path = "/wiki/"

[[en.origin]]
name = "Warcraft Wiki - Neoseeker"
url = "warcraft.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.origin]]
name = "World of Warcraft Wiki - Neoseeker"
url = "wow.neoseeker.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Warcraft Wiki"
host = "wiki.gg"
url = "warcraft.wiki.gg"
platform = "mediawiki"
icon = "warcraftwiki.png"
mainpage = "Warcraft_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
