[en]
name = "White Knuckle"
icon = "whiteknucklewiki.png"

[[en.origin]]
name = "White Knuckle Fandom Wiki"
url = "white-knuckle.fandom.com"
mainpage = "White_Knuckle_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "White Knuckle Wiki"
host = "Miraheze"
url = "whiteknuckle.miraheze.org"
platform = "mediawiki"
icon = "whiteknucklewiki.png"
mainpage = "White_Knuckle_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
tags = [
    "recommended",
]
