[en]
name = "Will You Snail?"
icon = "willyousnailwiki.png"

[[en.origin]]
name = "Will You Snail? Fandom Wiki"
url = "willyousnail.fandom.com"
mainpage = "Will_You_Snail?_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Will You Snail Wiki"
host = "wiki.gg"
url = "willyousnail.wiki.gg"
platform = "mediawiki"
icon = "willyousnailwiki.png"
mainpage = "Will_You_Snail_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
tags = [
    "official",
]
