[en]
name = "Witch Hat Atelier"
icon = "witchhatatelierwiki.png"

[[en.origin]]
name = "Witch Hat Atelier Fandom Wiki"
url = "witch-hat-atelier.fandom.com"
mainpage = "Witch_Hat_Atelier_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Witch Hat Atelier Wiki"
host = "Telepedia"
url = "witchhatatelier.telepedia.net"
platform = "mediawiki"
icon = "witchhatatelierwiki.png"
mainpage = "Witch_Hat_Atelier_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
