[en]
origins_label = "Witchfire Fandom Wiki"
destination = "Witchfire Wiki"
destination_base_url = "witchfire.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "witchfirewiki.png"
destination_main_page = "Main_Page"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Witchfire Fandom Wiki"
origin_base_url = "witchfire.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Witchfire_Wiki"
