[en]
name = "Witchfire"
icon = "witchfirewiki.png"

[[en.origin]]
name = "Witchfire Fandom Wiki"
url = "witchfire.fandom.com"
mainpage = "Witchfire_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Witchfire Wiki"
host = "wiki.gg"
url = "witchfire.wiki.gg"
platform = "mediawiki"
icon = "witchfirewiki.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/wiki/"
