[en]
name = "Wizardry"
icon = "wizardrywiki.png"

[[en.origin]]
name = "Wizardry Fandom Wiki"
url = "wizardry.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "Wizardry Wiki"
host = "wiki.gg"
url = "wizardry.wiki.gg"
platform = "mediawiki"
icon = "wizardrywiki.png"
mainpage = "Wizardry_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
