[en]
name = "World Trigger"
icon = "worldtrigger.png"

[[en.origin]]
name = "World Trigger Fandom Wiki"
url = "worldtrigger.fandom.com"
mainpage = "Main_Page"
content-path = "/wiki/"

[[en.destination]]
name = "World Trigger Wiki"
host = "Miraheze"
url = "worldtriggerwiki.com"
platform = "mediawiki"
icon = "worldtrigger.png"
mainpage = "Welcome_to_the_World_Trigger_Wiki"
search-path = "/w/index.php"
content-path = "/wiki/"
