[en]
origins_label = "Wesley's Roguelike Dungeons Fandom Wiki"
destination = "Wesley's Roguelike Dungeons Wiki"
destination_base_url = "wesleysroguelikedungeons.wiki.gg"
destination_platform = "mediawiki"
destination_icon = "wesleysroguelikedungeonsmodwiki.png"
destination_main_page = "Wesley's_Roguelike_Dungeons_mod_Wiki"
destination_search_path = "/index.php"
destination_content_path = "/wiki/"
destination_host = "wiki.gg"

[[en.origins]]
origin = "Wesley's Roguelike Dungeons Fandom Wiki"
origin_base_url = "wrdminecraft.fandom.com"
origin_content_path = "/wiki/"
origin_main_page = "Wesley's_Roguelike_Dungeons_mod_Wiki"
