[en]
name = "Wesley's Roguelike Dungeons"
icon = "wesleysroguelikedungeonsmodwiki.png"

[[en.origin]]
name = "Wesley's Roguelike Dungeons Fandom Wiki"
url = "wrdminecraft.fandom.com"
mainpage = "Wesley's_Roguelike_Dungeons_mod_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Wesley's Roguelike Dungeons Wiki"
host = "wiki.gg"
url = "wesleysroguelikedungeons.wiki.gg"
platform = "mediawiki"
icon = "wesleysroguelikedungeonsmodwiki.png"
mainpage = "Wesley's_Roguelike_Dungeons_mod_Wiki"
search-path = "/index.php"
content-path = "/wiki/"
