[en]
name = "Wyvern"
icon = "wyvernsource.png"

[[en.origin]]
name = "Wyvern Fandom Wiki"
url = "wvyernrpg.fandom.com"
mainpage = "Wyvern_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Wyvern Source"
url = "wiki.wyvernsource.com"
platform = "mediawiki"
icon = "wyvernsource.png"
mainpage = "Main_Page"
search-path = "/index.php"
content-path = "/index.php/"
