[en]
name = "Yume Nikki"
icon = "yumenikkiwiki.png"

[[en.origin]]
name = "Yume Nikki Fandom Wiki"
url = "yumenikki.fandom.com"
mainpage = "Yume_Nikki_Wiki"
content-path = "/wiki/"

[[en.destination]]
name = "Yume Nikki Wiki"
url = "yume.wiki"
platform = "mediawiki"
icon = "yumenikkiwiki.png"
mainpage = "Yume_Nikki_Wiki"
search-path = "/index.php"
content-path = "/"
